### ISSUE TITLE
DemiGod not available

### ISSUE THREAD

**Issue by roshin8** [oasisfeng/island#103]
I'm using version 4.5.1. 
I cannot see DemiGod in my options.
Also, accessing Personal Storage is also not working in Island mode for Messenger App

**Comment by oasisfeng** [comment]
Demigod mode is not a visible option in Island UI, it has to be activated via ADB shell. After mode activation, you can perform various actions (e.g. freezing) on apps in Mainland.

**Comment by roshin8** [comment]
Can you provide instructions on how to activate DEMIGOD mode?

**Comment by oasisfeng** [comment]
https://github.com/oasisfeng/island/blob/gh-pages/setup.md#manual-setup-for-island-in-god-mode--demigod-mode
