### ISSUE TITLE
4.5.1进主页卡死 

### ISSUE THREAD

**Issue by h251w** [oasisfeng/island#104]
4.5.1进主页卡死 
![Screenshot_20200619-115937](https://user-images.githubusercontent.com/67063992/85095588-6a49a700-b224-11ea-84a0-1fe065aa8bb4.jpg)

**Comment by oasisfeng** [comment]
能否提供一份问题出现后立即生成的 bugreport（故障报告）？一般可在开发者选项中找到「创建故障报告」，在弹出菜单中选择「完整报告」。

了解如果获得 logcat 日志的话，也可以直接发 logcat 日志文件给我。

**Comment by h251w** [comment]
抱歉
用核心破解换到4.1.1了
....

oasisfeng <notifications@github.com> 於 2020年6月19日 週五 17:43 寫道：

**Comment by oasisfeng** [comment]
v4.5.2 已修复
