### ISSUE TITLE
Island app removed from play store

### ISSUE THREAD

**Issue by arjuntsgowda** [oasisfeng/island#105]
Island app has been suddenly removed from play store...Is there a specific reason for it to get removed??

**Comment by oasisfeng** [comment]
Due to violation of Google Play Policy section 4.5.

> We don’t allow apps in Google Play to distribute or make available any Product which has a purpose that facilitates the distribution of software applications and games for use on Android devices outside of Google Play.

**Comment by arjuntsgowda** [comment]
Ur app didn't facilitate me to install any apps or games...😂
Is there any way where it can be made available after clarification on play Store or can it be made available on fdroid or something??

**Comment by oasisfeng** [comment]
> Ur app didn't facilitate me to install any apps or games...😂
> Is there any way where it can be made available after clarification on play Store or can it be made available on fdroid or something??

Probably linked to the "Featured" tab of Island.

Don't worry. I'm working on bring to back to Play Store.

**Comment by abelbabel** [comment]
> Don't worry. I'm working on bring it to back to Play Store.

What about [F-Droid](https://github.com/f-droid)?
If Island does not fulfill the [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/), you could provide your own F-Droid repository [like microG does](https://microg.org/download.html).

**Comment by oasisfeng** [comment]
> What about [F-Droid](https://github.com/f-droid)?
> If Island does not fulfill the [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/), you could provide your own F-Droid repository [like microG does](https://microg.org/download.html).

Thanks for the suggestion, I will evaluate this solution.

**Comment by oasisfeng** [comment]
Island is now back to normal on Google Play Store.

**Comment by AndroidDeveloperLB** [comment]
@oasisfeng Where exactly?
Can you please put a link on the repository's page?

**Comment by Hydra119** [comment]
I got a notification about the Island App, being removed from Google Play Store. But, this is a year-old thread, and I only just got this?

https://www.mediafire.com/file/e2zbo529mx00car/scv20210602_174636.png/file
