### ISSUE TITLE
'Clone' of an app does not work

### ISSUE THREAD

**Issue by freebrowser1** [oasisfeng/island#109]
I installed Island, then I issued ADB commands to preserver App Ops for frozen apps.
I got to the Mainland, clicked on an app and then on 'Clone' below right.

The first app then a popup appeared it was doing like 'installing' an app and then it finished, but sometimes it takes ages. But could not find the app in the Island. All subsequent cloning attempts did nothing at all.

What am I doing wrong ?

Hardware : Xiaomi Mi Pro 8 running stock Android 10 (MIUI 11).
Island app v4.54 from the Dropbox link in XDA Developers thread.

EDIT: I cleaned up the app and set it up again and now I got the message 'installing' the app, but after some time (several minutes) I got the message 'Failed', 'Canceled by user' while I did not cancel anything. Find attached screenshots.
And the 'alternatve way' did not work either.

![Screenshot_2020-07-04-21-45-09-082_com oasisfeng island](https://user-images.githubusercontent.com/26625141/86519988-49966980-be40-11ea-90b7-51a36fc59dbb.jpg)
![Screenshot_2020-07-04-21-26-27-010_com oasisfeng island](https://user-images.githubusercontent.com/26625141/86519990-4ac79680-be40-11ea-8e5d-f655c0b1d3ba.jpg)

**Comment by oasisfeng** [comment]
Sorry, there's a known cloning issue on MIUI, I'm working on it.

**Comment by freebrowser1** [comment]
Indeed, I installed it successfully on the OnePlus 6, no issues.
Ticket can be closed.

**Comment by MR-RUST** [comment]
> Sorry, there's a known cloning issue on MIUI, I'm working on it.

did u fixed it???

**Comment by oasisfeng** [comment]
> > Sorry, there's a known cloning issue on MIUI, I'm working on it.
> 
> did u fixed it???

Already fixed in the alpha version.
