### ISSUE TITLE
冻结壶中界中所有默认克隆的系统应用，导致手机无限重启

### ISSUE THREAD

**Issue by 2051783131** [oasisfeng/island#112]
冻结壶中界中所有默认克隆的系统应用，卸载炼妖壶，导致手机自动无限重启。强制重启后，只要解开锁屏密码，则重启。

**Comment by oasisfeng** [comment]
反馈这种问题，至少说明一下机型、ROM、Android 版本。

如果需要分析原因，还需要 logcat 日志。

**Comment by 2051783131** [comment]
> 反馈这种问题，至少说明一下机型、ROM、Android 版本。
> 
> 如果需要分析原因，还需要 logcat 日志。


荣耀7a，版本号AUM-AL00 8.0.0.218(C00)，安卓版本8.0.0。手机重置了，日志也没了🙃

**Comment by oasisfeng** [comment]
默认克隆的系统应用是设备 ROM 设定的要求，非 Island 的设计，冻结这些系统应用可能导致无法预知的后果。

**Comment by ssinacom** [comment]
多余

**Comment by ssinacom** [comment]
m.youlai.cn

**Comment by ssinacom** [comment]
[]()m.youlai.cn

**Comment by ssinacom** [comment]
[m.youlai.cn]()
