### ISSUE TITLE
成功开启炼妖壶后无壶中界选项

### ISSUE THREAD

**Issue by Xaiver97** [oasisfeng/island#114]
开发大大您好：
我手机型号是三星S10+，安卓10，成功通过ADB命令开启炼妖壶后无壶中界选项，到网上搜了一圈好像也没有类似的情况，所以只能来Git发Issue求助，感谢！！
![Screenshot_20200724-193614_Island](https://user-images.githubusercontent.com/46915084/88394663-66e0a700-cdf2-11ea-9696-4f9b59f58abc.jpg)
![Screenshot_20200724-193637_Android System](https://user-images.githubusercontent.com/46915084/88394673-6d6f1e80-cdf2-11ea-861c-8ed41a9303ce.jpg)

**Comment by gmrsuns** [comment]
我用遇到了同样得问题，我是通过adb工具安装得，手机也是S10 （已root）
使用得命令为：
dpm set-profile-owner --user 0 --name Mainland com.oasisfeng.island/.IslandDeviceAdminReceiver
island可以启动，能看到天书和 界外。但没有壶中界

**Comment by oasisfeng** [comment]
你们开启的是 对界外的接管，并没有创建 壶中界。

创建壶中界的文档指引：
https://github.com/oasisfeng/island/blob/gh-pages/setup.md#manual-setup-for-island
