### ISSUE TITLE
TWRP Decrypt user profile password

### ISSUE THREAD

**Issue by webtroter** [oasisfeng/island#116]
Hi,

TWRP recently added user profiles decryption feature into the recovery. This will fix the previous impossibility to backup Android when a work profile is enable.

TWRP asks for a password to decrypt the workprofile.

Can we obtain this password somehow ?

Thanks

**Comment by oasisfeng** [comment]
Sorry, no clue about that.

**Comment by runalsh** [comment]
i found how make it.
you should go to settings - password and secuirity and uncheck box named "use one lock method for work profile and device screen".
after than setup grapfic key for working profile.

now y can go to twrp and decrypt user island (10) and backup it

**Comment by webtroter** [comment]
I do confirm with an up to date TWRP I can backup(and successfully) work profiles when setting a password for the lock profile (can be the same, still had to type it twice in twrp).

I you come across this, you could include it in some kind of FAQ.
