### ISSUE TITLE
notification panel and developer options running error

### ISSUE THREAD

**Issue by TripixBlade** [oasisfeng/island#118]
I have a meizu 16th running flyme8.20.6.30 beta(deeply modified android 8.1.0), after setting island the device owner, I cannot pull out the notification panel except using home screen gesture, and notifications stops showing in the notification panel, that is, the notification panel is always empty even if it should have something on it.
And  developer options is empty when I enter it, just a white screen. And adb and mtp are not running, I cannot connect my phone to my computer.

**Comment by oasisfeng** [comment]
Make sure you have executed this command mentioned in setup guide:

`settings put global device_provisioned 1`

**Comment by TripixBlade** [comment]
THANKS, everything is normal again!
