### ISSUE TITLE
Please remove "Island Settings" launcher icon

### ISSUE THREAD

**Issue by Sughosha** [oasisfeng/island#123]
Is "Island Settings" app launcher icon necessary? If I want to go to settings I go from within the app. As the icon is showed as a _Work Profile_ app, the launcher I use doesn't have option to hide a work profile app. Please remove "Island Settings" launcher icon.

**Comment by oasisfeng** [comment]
Sorry, it plays a critical role in Island cross-space mechanism, thus cannot be removed.
