### ISSUE TITLE
5.0 Instant Crash

### ISSUE THREAD

**Issue by nicpadilla** [oasisfeng/island#124]
Updated from v4.5.4 to v5.0. The app now crashes immediately with no way of accessing the island environment. Is there a way to recover settings/data or revert to v4.5.4? Downgrading via adb (e.g. adb shell pm install -r -d [apk location]) does not work.

**Comment by oasisfeng** [comment]
Sorry for the trouble. It's now fixed in v5.1. (alpha channel)

**Comment by oasisfeng** [comment]
Planned to support update rollback feature in the future. (not just Island itself)
