### ISSUE TITLE
5.1 after phone restart, all linkages for apps in island fail

### ISSUE THREAD

**Issue by kevinlyliu** [oasisfeng/island#127]
Pixel 2 XL android 10 unrooted

After upgraded to 5.1, all linkages to apps in island fail, show error message: app isn't installed.

Then I re-made the linkages, all seems good. While after restart the phone, linkages fail appear again.

**Comment by oasisfeng** [comment]
Fixed in v5.1.1.

**Comment by Veazer** [comment]
I'm having the same issue but there was no OS update on my phone. The problem appears to have started when island is upgraded to 5.1.2.  About 50% of the launcher icons work and 50% don't. For apps that have the issues, re-creating the icons does _not_ fix the problem. Likewise, re-creating the launch icons for working apps does not cause them to break and the new launcher works as well.

Moto G5plus (potter) running stock 8.1.0
