### ISSUE TITLE
In island WeChat can not load mini-programe

### ISSUE THREAD

**Issue by ghubxyz** [oasisfeng/island#128]
system: Android 10
phone: Sony Xperia 1 ii
Island:  4.5.4

Cannot load mini-programe when running WeChat in island area

**Comment by Fingalzzz** [comment]
According to the author, try to copy the files in `/storage/emulated/0/Android/obb/com.tencent.mm/` to '/storage/emulated/<user_id>/Android/obb/com.tencent.mm/`.
That fix for me.

**Comment by ghubxyz** [comment]
> According to the author, try to copy the files in `/storage/emulated/0/Android/obb/com.tencent.mm/` to `/storage/emulated/<user_id>/Android/obb/com.tencent.mm/`.
> That fix for me.
Thx . The problem is solved.
