### ISSUE TITLE
island 启用 设备管理员 命令不起作用

### ISSUE THREAD

**Issue by om2mo** [oasisfeng/island#131]
<img width="1040" alt="2020-08-24 06_33_23-Setup Guide" src="https://user-images.githubusercontent.com/4419299/90990458-2a13f580-e5d4-11ea-9568-d23e7e4c26f1.png">

**Comment by oasisfeng** [comment]
Some devices / ROMs impose restrictions on the modification of system properties.

Try skipping that step. If you are lucky, it will still work.
