### ISSUE TITLE
[Question] How to upgrade an Island app ?

### ISSUE THREAD

**Issue by KaKi87** [oasisfeng/island#136]
Hello,

How do I upgrade an app that is only installed in island ?

Thanks

**Comment by neodada** [comment]
Update through play store. Or manually install apk file inside island.

**Comment by KaKi87** [comment]
Managing apps using Play Store auto updates requires the app to be also installed in mainland, right ?
Is there any way to bring automated updates to island ?
I have very high privacy concerns about one of the apps I use in island and I'm pretty sure that the simple act of installing it is enough for it to start collecting data. 
So, APK it is I suppose.

**Comment by KaKi87** [comment]
I can't find the option to install an APK ?

**Comment by neodada** [comment]
Activate File Shuttle. Than use Files app to launch apk install.
Or when you open apk you will get an option to open with Island's App installer. That will install both in mainland and island.

**Comment by B-A-K-A-03** [comment]
I can't uninstall the app, when I enter "Settings" and click "Scoped settings" nothing happens... That sucks.

**Comment by KaKi87** [comment]
Where do I find the File Shuttle ?

**Comment by neodada** [comment]
Discovery >> File Shuttle. https://island.oasisfeng.com/files

File Shuttle is required if you want to access files of Mainland from Island.

**Comment by oasisfeng** [comment]
> Managing apps using Play Store auto updates requires the app to be also installed in mainland, right ?
> Is there any way to bring automated updates to island ?
> I have very high privacy concerns about one of the apps I use in island and I'm pretty sure that the simple act of installing it is enough for it to start collecting data.
> So, APK it is I suppose.

You can simply clone Play Store in the Island to let it upgrade all apps inside. Play Store is smart enough to avoid double-upgrade inside and outside Island.

**Comment by KaKi87** [comment]
Wow, the Play Store works inside Island?
That's amazing, I wouldn't have believed that Google would let that happen.
But, I can't do it, because that would ruin the privacy I'm looking for.
I'll try an alternative app like Aurora or Aptoide then.
Thanks!
