### ISSUE TITLE
[feature suggestion] add support / integration of VirtualXposed 

### ISSUE THREAD

**Issue by tonsimple** [oasisfeng/island#14]
Hi! 
Just a humble feature suggestion: add integration / support of VirtualXposed https://github.com/android-hacker/VirtualXposed

Technically, it already works (I installed it into Island, didn't test much tho...but it's a wee bit clunky _(Island ->VE's-"container"-with-its-own-launcher->app)_  and it would be neat if there was a way to get VirtualXposed's rootless Xposed-hooking functionality with slightly less clutter

**Comment by oasisfeng** [comment]
Sorry, they works in completely different ways. It's not feasible to integrate VirtualXposed.
