### ISSUE TITLE
Text overflow on Discovery tab

### ISSUE THREAD

**Issue by khorser** [oasisfeng/island#144]
Hi, for some reason DISCOVERY tab looks like "DISCOVER Y" with Y on the second line (see [screenshot](https://user-images.githubusercontent.com/1499958/92715962-d8ef5a00-f366-11ea-9deb-66a62a5836c6.png)). I think it would look much better cropped.

**Comment by oasisfeng** [comment]
Thanks for the report, it surely needs to be fixed.
