### ISSUE TITLE
Shortcut to island'ed app no longer works

### ISSUE THREAD

**Issue by guanzhangrtk** [oasisfeng/island#145]
First of all, great app. I've previously used other "similar" apps on Bluestacks and they don't work, now I can launch the same app with different credentials in the same Bluestacks instance.

I believe when I first installed island and added an app to it, a shortcut was created and that was able to start the app in the island. The shortcut to mainland also works fine. However, there was a data update for the app (not from store, but it just loaded some new data internally via the app) and since then the shortcut which should link to the one in island now links to mainland.

I suppose I could just re-create the shortcut, but thought perhaps I've encountered a bug or something, thanks in advance for any insight.

**Comment by oasisfeng** [comment]
Fixed in the upcoming version.
