### ISSUE TITLE
Remove God Mode

### ISSUE THREAD

**Issue by mehedihasanziku** [oasisfeng/island#149]
I would like to remove god mode or turned off, how to do that?

**Comment by oasisfeng** [comment]
https://github.com/oasisfeng/island/blob/gh-pages/setup.md#deactivate-god--demigod-mode

**Comment by mehedihasanziku** [comment]
scroll to the bottom, click "Deactivate".

Where it is?

still showing same in both mode, only "setup", no deactivate option

**Comment by oasisfeng** [comment]
If it shows "Setup" instead of "Deactivate", that means Island is currently not in God mode.

**Comment by mehedihasanziku** [comment]
Then we should leave it like that? no process to remove that?
