### ISSUE TITLE
App Icons for Frozen apps disappear after freezing app. 

### ISSUE THREAD

**Issue by ching-chong04** [oasisfeng/island#150]
After updating the app from 4.5.4 to 5.1, I can't create new shortcuts for new frozen apps in Mainland, and ALL Cloned Apps Shortcut doesn't work either. I think it's because of the NEW **"Dynamic Shortcut Maker"** that causes this issue, that feature doesn't play with my launcher very nicely.  Can you create the new version without it? (Or atleast make a toggle in the settings to change it to the one you used in 4.5.4)

**Comment by oasisfeng** [comment]
Fixed in the upcoming version.
