### ISSUE TITLE
Were is the keyboard?

### ISSUE THREAD

**Issue by pippo73** [oasisfeng/island#152]
I've finished to install island, and "migrated" some apps, but when I have to write something in them, keyboard does not appear?
How can I fix it?

**Comment by breakplus** [comment]
I have the same problems. I use Redmi K30 Pro MIUI 12

**Comment by MR-RUST** [comment]
I can't even clone any app on my note 8 pro

**Comment by oasisfeng** [comment]
> I've finished to install island, and "migrated" some apps, but when I have to write something in them, keyboard does not appear?
> How can I fix it?

For Android 11+, you need to clone the IME app.

**Comment by mvanengel** [comment]
Hey mister, you're spamming me with emails. One is enough pls.

**Comment by leedsen** [comment]
> 我有同样的问题。我使用Redmi K30 Pro MIUI 12

解决了吗？

**Comment by djuby** [comment]
What is the IME app?
