### ISSUE TITLE
关机重启快捷方式无法启动

### ISSUE THREAD

**Issue by ABCxiaoxu** [oasisfeng/island#153]
机型: Pixel 3 XL
Android: Android 11
版本号: RP1A.201005.004
Island: v5.1
关机重启快捷方式无法启动 , Toast显示 “未安装该应用” .

Island: v4.5.4
关机重启后快捷方式无法打开 , 需要从 炼妖壶 / 界外 重新打开一遍才能使快捷方式生效 ( 恢复 “解冻并启动” 和冻结功能 ) . 

建议:
可以的话修复一下 & 添加一个用户 / 系统 / 冻结 类目 , 不然的话每次无法启动都需要下滑到最底下一个个打开.

**Comment by oasisfeng** [comment]
Fixed in the upcoming version.
