### ISSUE TITLE
Failed to Install:- INSTALL_FAILED_USER_RESTRICTED: Failed INSTALL_CANCELLED_BY_USER

### ISSUE THREAD

**Issue by MR-RUST** [oasisfeng/island#154]
I have Redmi Note 8 pro with Android 10(Q) AND MI 12.0.2
whenever i want to clone any app, it says Failed to install 
INSTALL_FAILED_USER_RESTRICTED: : Failed INSTALL_CANCELLED_BY_USER
Anyone knows the fix for this?

**Comment by oasisfeng** [comment]
It's a bug in MIUI. Until MIUI fixes this compatibility issue, the only solution is "Disable MIUI optimization" in system "Settings - Developer options".
