### ISSUE TITLE
无法安装：-INSTALL_FAILED_USER_RESTRICTED：无法安装INSTALL_CANCELLED_BY_USER

### ISSUE THREAD

**Issue by MR-RUST** [oasisfeng/island#155]
我有配备Android 10（Q）和MI 12.0.2的Redmi Note 8 pro
每当我想要克隆任何应用程序时，它都说无法安装
INSTALL_FAILED_USER_RESTRICTED：：失败INSTALL_CANCELLED_BY_USER
任何人都知道

**Comment by oasisfeng** [comment]
这是 MIUI 的 bug，只能通过关闭「开发者选项」下的 MIUI 优化才能解决。
