### ISSUE TITLE
After turning off work profile notification still coming in android 11 custom rom

### ISSUE THREAD

**Issue by arkaroy14** [oasisfeng/island#161]
I am using android 11 nitrogen os on realme x2 pro . But i notice after turning off work profile apps are not stopped still sending notifications. Is any issue with android 11 or having issue with custom rom?
Got some logs:

1274

PackageMa

nager

8393

ActivityM

anager

15057

RecentApp

StatsMixi

n

11-02 01:12:09.531

Cannot suspend package "com.oasisfeng.island": has an active

device admin

11-02 01:16:50.100

Start proc 13066: com.oasisfeng. island/ u12a247 for service {com.oasisfeng.island/com.oasisfeng.isla nd.service. IslandPersistentService}

11-02 01:19:55.915

D Invalid timestamp (usage time is more than 24 hours ago), skipping com.oasisfeng.island

**Comment by oasisfeng** [comment]
Probably just push notifications posted by the "push" module of your ROM system, not the app itself.

**Comment by arkaroy14** [comment]
For example i have whatsapp on island work space and after turning off work profile app stops working but in android 11 many times after turning off work profile whatsapp running on work space as i can send message to that number also receive that notification even if i turned off work profile.
Never faced this issue previously in android 10 roms. 😊

**Comment by arkaroy14** [comment]
This issue somewhat conflicting with magisk. Now no issue.
