### ISSUE TITLE
Unable to get island to work on my Xiaomi Pocophone F1 No root

### ISSUE THREAD

**Issue by FCsean** [oasisfeng/island#17]
Check build.prop via adb seems like max_users and multiuserui isn't there.
```
1|beryllium:/ $ setprop fw.max_users 10
setprop: failed to set property 'fw.max_users' to '10'
```
Getting the issue above.

**Comment by oasisfeng** [comment]
Island should work normally on Android 8+ without the need for ADB. Just setup as normal.

If you prefer ADB, MIUI has a security-related setting for ADB in development settings. Be sure to turn it on before running the command above.

**Comment by FCsean** [comment]
When I startup Island, it says `Can't set up profile`, `Couldn't set up your owrk profile. Contact your IT department or try again later.`

I've done the following:
`Settings - Additional settings - Developer options”, enable “USB debugging (Security settings)`
`Settings - Permissions - Autostart”, enable “Island`

But I'm still getting the issue on my initial post.

**Comment by oasisfeng** [comment]
That error message comes from the work profile setup component in your system, not Island.
It seems like your device is incompatible with the standard setup procedure of Android for Work.

Have you tried to setup manually via ADB commands, with "USB debugging (security settings)" enabled first?

**Comment by oasisfeng** [comment]
Closed due to lack of response.

**Comment by lmayai** [comment]
Hello everyone!

You have to Delete all dual apps data.
So go to: Settings - Apps - Dual apps  - Dual Apps Settings - Delete all dual apps.

It works perfectly for me, after that was possible set up my work profile in my Xioami Pocophone with Android 9 and Miui 11.

**Comment by Phusionraze** [comment]
I myself faced this issue on my Moto One Action (Android 10) when attempting to set up God Mode as described in [the online guide](https://island.oasisfeng.com/setup.html). 

"pm create-user --profileOf 0 --managed Island" returned "Error: Couldn't create user." and "setprop fw.max_users 10" returned "setprop: failed to set property 'fw.max_users' to '10'". I initially tried to delete Island's island profile per Imaya's suggestion, but only managed to get "pm create-user --profileOf 0 --managed Island" to work (returning "Success: created user id 12") after toggling off multiple users in system settings (as was the case for [this XDA user](https://forum.xda-developers.com/showpost.php?p=75016282&postcount=576) I wasn't able to actually delete the "guest" user, but I could toggle the setting by the upper-right switch seen in [this example image](https://www.online-tech-tips.com/wp-content/uploads/2019/11/android-switch-user-account.png)).

"setprop fw.max_users 10" still returns "setprop: failed to set property 'fw.max_users' to '10'", however I guess that is no problem anymore.
