### ISSUE TITLE
Feature request: support auto fill

### ISSUE THREAD

**Issue by ivysrono** [oasisfeng/island#172]
Some discussion: https://github.com/Kunzisoft/KeePassDX/issues/526#issuecomment-738829227

> an external app service is never activated (regardless of the application with autofill) in the island profile settings (always returns to none).

**Comment by oasisfeng** [comment]
I have tested LastPass, it's AutoFill functionality works in Island just fine.

You need to activate it first in system **Settings - System - Autofill - Work profile.**

**Comment by ivysrono** [comment]
In fact, our original intention is whether it can be achieved without cloning the application.
Thank you very much anyway.

**Comment by oasisfeng** [comment]
> In fact, our original intention is whether it can be achieved without cloning the application.
> Thank you very much anyway.

That's not possible, considering the hard isolation of work profile.
But apps can still request "cross profile" privilege to communicate between instances, on Android 11+.

**Comment by ivysrono** [comment]
> But apps can still request "cross profile" privilege to communicate between instances, on Android 11+.

The 'apps' means KeePass/Lastpass and so on?

**Comment by oasisfeng** [comment]
> > But apps can still request "cross profile" privilege to communicate between instances, on Android 11+.
> 
> The 'apps' means KeePass/Lastpass and so on?

Yes
