### ISSUE TITLE
关于一加手机的兼容性问题

### ISSUE THREAD

**Issue by huangsijun17** [oasisfeng/island#175]
**_因为试了好多方法，所以issue有点长……抱歉。_**

一加的氢OS（国行预装系统）默认会存在一个登陆用户，导致God Mode无法开启：
```
OnePlus8T:/ # dpm set-device-owner com.oasisfeng.island/.IslandDeviceAdminReceiver
java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8665)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9669)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8710)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3582)
        at android.os.Binder.execTransactInternal(Binder.java:1165)
        at android.os.Binder.execTransact(Binder.java:1134
```

`dumpsys account|grep -A 3 Accounts:`命令显示存在：
`Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
由于手机有root权限，我就在adb shell中尝试提权运行了：
```
pm uninstall com.oneplus.account_ACCOUNT_NAME
pm hide com.oneplus.account_ACCOUNT_NAME
pm unhide com.oneplus.account_ACCOUNT_NAME
```
然后开启God Mode又出现了问题：
`… Not allowed to set the device owner because there are already several users on the device`
（尝试过，开启Demigod mode可以开启）
必须用`pm remove-user 10`删除壶中界。

但是删完后，命令行无法重新修建，在炼妖壶的天书中修建报错如图：
![image](https://user-images.githubusercontent.com/31504595/102157423-6ee0d680-3eba-11eb-9375-b39d187f4df4.png)

**环境信息：**
一加8T
安卓11
Hydrogen OS 11.0.6.8.KB05
Magisk 版本:21.1(21100) A/B:是 SAR:是 Ramdisk:是 Crypto:File
炼妖壶 5.1.2

**Comment by qzgq** [comment]
我也是一加8T氢OS，遇到了同样的问题，请问刷氧OS能解决吗？

**Comment by huangsijun17** [comment]
> 我也是一加8T氢OS，遇到了同样的问题，请问刷氧OS能解决吗？

我没有试过……

**Comment by Sakura-Space** [comment]
俺也一样

**Comment by JiZhi-Error** [comment]
看来没root是弄不了

**Comment by oasisfeng** [comment]
> `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。

这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。

**Comment by JiZhi-Error** [comment]
> > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> 
> 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。

Users这边删了后 Account那边也得删

**Comment by JiZhi-Error** [comment]
> > > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> > 
> > 
> > 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。
> 
> Users这边删了后 Account那边也得删

而且在Android 11上，没有root权限，没法执行hide
![image](https://user-images.githubusercontent.com/24365406/112555910-0f249080-8e04-11eb-9cfd-8c671e715f74.png)

**Comment by huangsijun17** [comment]
> > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> 
> 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。

该应用为系统应用，默认就强制存在一个账户，用于防盗定位等。账户无法注销，应用管理中清除所有数据都不行。
我找到的方法只有`adb hide`命令。

**Comment by JiZhi-Error** [comment]
> > > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> > 
> > 
> > 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。
> 
> 该应用为系统应用，默认就强制存在一个账户，用于防盗定位等。账户无法注销，应用管理中清除所有数据都不行。
> 我找到的方法只有`adb hide`命令。

是的，然而hide不行，得root

**Comment by huangsijun17** [comment]
另外，安卓11下God Mode和多开可以同时存在了吗？

**Comment by huangsijun17** [comment]
> > > > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > > > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> > > 
> > > 
> > > 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。
> > 
> > 
> > 该应用为系统应用，默认就强制存在一个账户，用于防盗定位等。账户无法注销，应用管理中清除所有数据都不行。
> > 我找到的方法只有`adb hide`命令。
> 
> 是的，然而hide不行，得root

只是因为`adb hide`和`pm hide`都需要root权限才能运行。

**Comment by JiZhi-Error** [comment]
> > > > > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > > > > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> > > > 
> > > > 
> > > > 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。
> > > 
> > > 
> > > 该应用为系统应用，默认就强制存在一个账户，用于防盗定位等。账户无法注销，应用管理中清除所有数据都不行。
> > > 我找到的方法只有`adb hide`命令。
> > 
> > 
> > 是的，然而hide不行，得root
> 
> 只是因为`adb hide`和`pm hide`都需要root权限才能运行。

以前不需要，后来给堵了

**Comment by oasisfeng** [comment]
> > > `dumpsys account|grep -A 3 Accounts:`命令显示存在：
> > > `Account {name=com.oneplus.account_ACCOUNT_NAME, type=com.usercenter.account_ACCOUNT_TYPE}`，为一加账户APP。
> > 
> > 
> > 这是 Account，不是 User。 `pm list users` 可以列出所有 Users，开启 God mode 需要删除除第一个之外的其它 User。
> 
> 该应用为系统应用，默认就强制存在一个账户，用于防盗定位等。账户无法注销，应用管理中清除所有数据都不行。
> 我找到的方法只有`adb hide`命令。

可以尝试一下 Island 的 AdbShell： https://island.oasisfeng.com/adb

其中的 remove-account 指令也许可以帮到。

**Comment by olbb** [comment]
卸载一加账号恢复为出厂版本可以解决
一加这破应用真是把我恶心到了

**Comment by JiZhi-Error** [comment]
> 卸载一加账号恢复为出厂版本可以解决
> 一加这破应用真是把我恶心到了

但是对于后续的新机，新系统默认版本就这，无法恢复的

**Comment by qzgq** [comment]
还是考虑用shizuku配合其他软件取代炼妖壶的GodMod吧，安卓11用无线调试激活shizuku很方便的

于 2021年3月28日 GMT+08:00 上午8:08:11, "极致" ***@***.***> 写到:

**Comment by olbb** [comment]
> > 卸载一加账号恢复为出厂版本可以解决
> > 一加这破应用真是把我恶心到了
> 
> 但是对于后续的新机，新系统默认版本就这，无法恢复的

不清楚是因为降级版本的原因还是因为降级版本同时清除了应用数据的时候删除了这个账号
如果是因为清除数据删除了账号新rom应该也没问题
