### ISSUE TITLE
The message popped up in the app in Island has no details

### ISSUE THREAD

**Issue by penhauer-xiao** [oasisfeng/island#18]
The message popped up in the app in Island has no details, just open it and watch it；
This is the case for all kinds of applications. Click to go to app see the detailed message；

**Comment by oasisfeng** [comment]
Any screenshot?

**Comment by penhauer-xiao** [comment]
![screenshot_20190308-195914_samsung experience home](https://user-images.githubusercontent.com/6280121/54027835-d7772b80-41dd-11e9-8ea3-ba9240229247.jpg)
![screenshot_20190308-195922_samsung experience home](https://user-images.githubusercontent.com/6280121/54027838-d8a85880-41dd-11e9-85e5-1fa7c4b270d2.jpg)

**Comment by oasisfeng** [comment]
That's because your notification security settings (in system Settings - Security - Notification visibility) is set to "hidden before unlock" and the work profile unlock method is not set to be same with your device.

**Comment by penhauer-xiao** [comment]
I confirm that I have set it up in your way before this problem occurs; that is, it is not hidden. However, the application APP notification outside the Island is normal. But the app in Island is hidden.

![Screenshot_20190310-083401_Settings](https://user-images.githubusercontent.com/6280121/54079232-16a79880-4314-11e9-979a-78ea1a47aa26.jpg)

**Comment by oasisfeng** [comment]
![Screenshot_20190310-160100](https://user-images.githubusercontent.com/181213/54082317-76bb3080-434e-11e9-9f9b-8c6168736c44.png)

找找看你的手机设置中是否有图中标出的选项？

**Comment by penhauer-xiao** [comment]
奇怪，三星note8能用这个，但找不到这个选项

**Comment by oasisfeng** [comment]
可能三星对工作资料的安全更谨慎，没有提供这个选项……

你试试在 ADB shell 中执行这个指令：
`settings put --user 10 secure lock_screen_allow_private_notifications 1`

（其中 --user 后面的 10 需要改为你的设备上工作资料的实际用户 ID，可以通过 pm list users 查询）

**Comment by penhauer-xiao** [comment]
@oasisfeng 好的，谢谢
