### ISSUE TITLE
Unable to turn off message notifications in island.

### ISSUE THREAD

**Issue by penhauer-xiao** [oasisfeng/island#19]
For island Version 3.06, for each app, will turn off the notification, then freeze it, then, after unfreezing it, the notification opens itself. For example, Weibo

**Comment by oasisfeng** [comment]
Sorry, I don't understand exactly. What notification do you mean by? (Screenshot will be helpful)

**Comment by penhauer-xiao** [comment]
我用中文叙述一下吧，就是在Island中的应用，比如即使将微博的设置中的通知功能禁用了，接着将微博冻住，我发现它的通知禁用功能又被充许了，显示通知“已充许”；解冻后，微博照样弹出消息。这样岛内的应用一直无法禁用。

**Comment by penhauer-xiao** [comment]
![20190310_093427](https://user-images.githubusercontent.com/6280121/54079512-db5b9880-4318-11e9-80aa-78f398fbc3a8.jpg)

**Comment by penhauer-xiao** [comment]
![20190310_093552](https://user-images.githubusercontent.com/6280121/54079562-da773680-4319-11e9-80cc-89d5c52ed48a.jpg)

**Comment by penhauer-xiao** [comment]
![Screenshot_20190310-083416_Island](https://user-images.githubusercontent.com/6280121/54079565-e5ca6200-4319-11e9-9129-ab46eb7dfdcb.jpg)

**Comment by penhauer-xiao** [comment]
![Screenshot_20190310-083500_Settings](https://user-images.githubusercontent.com/6280121/54079597-7c971e80-431a-11e9-9659-1712a52bd526.jpg)

**Comment by oasisfeng** [comment]
很遗憾，通知设置在冻结后丢失的问题是 Android 8 的一个 bug，Island 在 Android 9 下已经可以无需 root 规避这个问题。但 Android 8 下需要 root 才能修复 Android 自身这个 bug（计划实现中）。

**Comment by penhauer-xiao** [comment]
太棒了， 等好消息了

**Comment by penhauer-xiao** [comment]
@oasisfeng  刚更新到最新的 island 3.6.2 问题依旧； 我的三星note8目前已升级到了android 9了； 不知道能否回更进一下

**Comment by oasisfeng** [comment]
On device running Android P+, the App Ops (including notification suppression) will be preserved after being unfrozen. For lower version of Android, this will be implemented with root privilege in the future version of Island.

**Comment by penhauer-xiao** [comment]
OK~  thanks @oasisfeng
