### ISSUE TITLE
“由于此设备已被XXX接管，壶中界无法创建”

### ISSUE THREAD

**Issue by Ru-kid** [oasisfeng/island#197]
【系统】 Android 8
【问题】
<img src='https://user-images.githubusercontent.com/56689882/111063881-f9ea6080-84eb-11eb-8230-18f7705ed56a.png' width='300px' />
这种创建工作空间的软件，只能使用一个吗

**Comment by eagle518** [comment]
只能单一接管

**Comment by Ru-kid** [comment]
> 只能单一接管
