### ISSUE TITLE
In the Island, the app store cannot detect the installed apps in Island.

### ISSUE THREAD

**Issue by penhauer-xiao** [oasisfeng/island#20]
In the Island, the app store cannot detect the installed apps in Island.   For example, Tencent App Store and Samsung App Store cannot detect the apps already installed in Island, so it is impossible to know whether to upgrade the apps.

**Comment by oasisfeng** [comment]
You need to install (or clone) the app store app inside Island.

**Comment by oasisfeng** [comment]
For frozen apps, currently only CoolApk could upgrade them (already featured in "Discover" tab).

**Comment by penhauer-xiao** [comment]
What is CoolApk?

**Comment by oasisfeng** [comment]
CoolApk is a 3rd-party app store in China: https://coolapk.com/

It has a lab feature "Show hidden apps" which will reveal frozen apps in Island.

**Comment by penhauer-xiao** [comment]
ok, thanks
