### ISSUE TITLE
无法通过壶内应用打开链接以及分享文件

### ISSUE THREAD

**Issue by spraysparks** [oasisfeng/island#208]
无法通过工作应用打开此内容
您的 IT 管理员不允许您通过工作资料中的应用打开此内容
![Screenshot_20210415-001707__01](https://user-images.githubusercontent.com/41980497/114744209-062e3b80-9d80-11eb-89ea-9be4c4a17d3e.jpg)

一加7 Pro, H2OS Android 11 beta

**Comment by spraysparks** [comment]
问题解决，关闭系统自带应用双开并删除双开用户后，可以正常分享到壶内。
推测应该是系统错将双开用户(999)当做炼妖壶用户(11)

**Comment by scruel** [comment]
MIUI 不管是否开启双开，都无法在主空间读写到工作文件…
