### ISSUE TITLE
Having the default branch be the unupdated master makes this project look abandoned

### ISSUE THREAD

**Issue by expipiplus1** [oasisfeng/island#214]
No updates for 3 years according to https://github.com/oasisfeng/island !

**Comment by hmnd** [comment]
This reoo should be archived, as it doesn't seem the project is open source anymore. Shelter is an actively open source alternative: https://cgit.typeblog.net/Shelter/.

**Comment by expipiplus1** [comment]
Oh, that's surprising as there seems to be activity on other branches!

**Comment by oasisfeng** [comment]
Sorry to have the default branch unmanaged for a long time, it's now synchronized to dev, as of the lastest release v5.3.

**Comment by expipiplus1** [comment]
Thanks!
