### ISSUE TITLE
小米6 lineage17.1无法在工作资料添加指纹

### ISSUE THREAD

**Issue by hutozh** [oasisfeng/island#215]
小米6 lineage.1，如果添加了普通用户指纹，就无法添加工作资料指纹，反之先添加工作资料指纹，就无法提交普通用户指纹。不知道是我系统不支持，还是其他问题。

**Comment by oasisfeng** [comment]
很可能是系统的问题，AOSP 测试环境和 Pixel 手机上尚未发现这个问题。

**Comment by hutozh** [comment]
> 很可能是系统的问题，AOSP 测试环境和 Pixel 手机上尚未发现这个问题。

换了一台一加官方系统，可以正常使用，应该就是lineage系统的问题了。

**Comment by TrayBer** [comment]
> 小米6 lineage.1，如果添加了普通用户指纹，就无法添加工作资料指纹，反之先添加工作资料指纹，就无法提交普通用户指纹。不知道是我系统不支持，还是其他问题。

同样遇到了这个问题，只能在普通用户、工作资料选择一个添加指纹，两处同时就会添加不上。
红米手机，使用 PixelExperience Android 11 类原生系统，但是重新刷系统这个代价有点大啊，如何修复这个问题呢？
