### ISSUE TITLE
Internal error: Shuttle not ready

### ISSUE THREAD

**Issue by midoriha-senpai** [oasisfeng/island#218]
When I try to clone any app, I get the error message prompted: "Internal error: Shuttle not ready". I just installed Island, so I'm not sure that I did anything to cause the problem.

I'm using a Samsung Galaxy S10e, running Android 11, current on all updates. I'll keep fiddling and let you know if something fixes the problem.

**Comment by midoriha-senpai** [comment]
Still no luck. I had to enable the File Shuttle ([island.oasisfeng.com/files](island.oasisfeng.com/files)), which I did, but now I'm getting a new error message: "Internal error: Unknown authority 11@com.oasisfeng.island.shuttle".

**Comment by midoriha-senpai** [comment]
I guess that my phone had "Work profile" turned off, which I did right before restarting my phone above. Once I enabled it and tried to clone again, I got a prompt stating that Island isn't allowed to install unknown apps, and brought me to a setting that I could toggle to allow it, so that's what I did. I tried one final time to clone, and it worked this time!

I'll close this issue now, thanks. 😅

**Comment by zane-sano** [comment]
I was with the same problem after reinstall the main app. But I just restarted my phone and it is ok.

**Comment by alexisnotavailab** [comment]
I have issue

**Comment by rocky308** [comment]
Hi bro i have the same problem
Internal error: Shuttle not ready
