### ISSUE TITLE
Linking / Redirection / Symbolic Links - Island cloned app filesystem to mainland filesystem

### ISSUE THREAD

**Issue by a1ch3mist** [oasisfeng/island#229]
I'd like to have my island app see a file system that is somehow nested on the mainland app.
Specifically, I want my Google Photos clone to see my camera filesystem separately than my mainland.

For example:
CLONE Photos, looks for camera as /storage/emulated/0/DCIM
which in reality on mainland is /storage/emulated/0/island/photoClone1/DCIM

Is there a way to do that?

My use case is to set up multiple Google Photos clones, so that each can be linked to a different Google account, and have them see the camera roll separately. Currently, each clone sees the same camera filesystem.

**Comment by oasisfeng** [comment]
I'm afraid that's technically not viable, as it breaks the isolation of work profile.
