### ISSUE TITLE
Feature Request: API for changing App Ops

### ISSUE THREAD

**Issue by JohnWang1023** [oasisfeng/island#23]
> Due to the exclusivity nature, user could only use one Android DPC app at a time, and price of switching DPC is far too heavy. To encourage active exploration and broader development in the capabilities of DPC and therefore better benefit users, Island is devoted to build an open collaboration for community developers, either in development of this project or opening DPC capabilities to 3rd-party apps via open API. Island itself will not focus on the rich set of features, but mainly focuses on building a powerful engine as an open platform for much more apps from the community.

Hi, this is just a feature suggestion: Add support for App Ops API in god mode so apps can use the API to change app ops without root or adb.

**Comment by oasisfeng** [comment]
Do you or you know any developer wish to build app ops features with these requested APIs? I'd like to discuss the API details in real world scenario.

**Comment by JohnWang1023** [comment]
I use the a app called  [权限狗 AppOps](https://www.coolapk.com/apk/com.web1n.permissiondog]) to change App Ops. It uses Device Owner mode from (小黑屋)[https://play.google.com/store/apps/details?id=web1n.stopapp] to change App Ops. I'd like to be able to use island with the app to change App Ops.

**Comment by oasisfeng** [comment]
Thanks for your information. I'm contacting the developer of the app you mentioned above to discuss the API requirements.

**Comment by JohnWang1023** [comment]
> Thanks for your information. I'm contacting the developer of the app you mentioned above to discuss the API requirements.

By the way the developer of 小黑屋 has a telegram account at web1n and a telegram group at t.me/stopapp_group

**Comment by penhauer-xiao** [comment]
@oasisfeng @JohnWang1023  I have also used App ops recently; but it seems that as long as it is frozen in the island and then unfrozen , App ops is considered a new application, and the previous settings will be lost.

**Comment by oasisfeng** [comment]
@penhauer-xiao On device running Android P+, the App Ops will be preserved after being unfrozen. For lower version of Android, this will be implemented with root privilege in the future version of Island.

**Comment by penhauer-xiao** [comment]
@penhauer-xiao  Ok

APP ops has a problem with invalid permissions. However, I probably know that the APP ops has been tested to invalidate the permissions.

**Comment by JohnWang1023** [comment]
Hi. I found this ([Delegated-Scopes-Manager](https://github.com/heruoxin/Delegated-Scopes-Manager)) from the developer of ice-box, it seem to be a way to share device administrator permissions, and it is based on the Android DevicePolicyManager.DELEGATION mechanism.

**Comment by oasisfeng** [comment]
> Hi. I found this ([Delegated-Scopes-Manager](https://github.com/heruoxin/Delegated-Scopes-Manager)) from the developer of ice-box, it seem to be a way to share device administrator permissions, and it is based on the Android DevicePolicyManager.DELEGATION mechanism.

I'm working on an future-proof and more flexible API design.

**Comment by oasisfeng** [comment]
New delegation-based API: https://island.oasisfeng.com/api

**Comment by isaackwan** [comment]
Piggybacking on this request, can I ask if you can open up additional delegated scopes, or even create a "God mode" scope where all `DevicePolicyManager` methods can be invoked?

For context: I am trying to create an app (for myself really) calling the `addUserRestriction` method so that non-Play-Store apps cannot be installed on the main profile.

This is the current list of supported delegated scopes:
```java
    private fun getSupportedDelegatedScope(delegation: String): Pair<String, Int>? {
        return delegation to when (delegation) {
            ApiConstants.DELEGATION_PACKAGE_ACCESS ->   R.string.label_delegation_package_access
            ApiConstants.DELEGATION_APP_OPS ->          R.string.label_delegation_app_ops
            else -> return null
        }
    }
```

**Comment by oasisfeng** [comment]
> Piggybacking on this request, can I ask if you can open up additional delegated scopes, or even create a "God mode" scope where all `DevicePolicyManager` methods can be invoked?
> 
> For context: I am trying to create an app (for myself really) calling the `addUserRestriction` method so that non-Play-Store apps cannot be installed on the main profile.
> 
> This is the current list of supported delegated scopes:
> 
> ```java
>     private fun getSupportedDelegatedScope(delegation: String): Pair<String, Int>? {
>         return delegation to when (delegation) {
>             ApiConstants.DELEGATION_PACKAGE_ACCESS ->   R.string.label_delegation_package_access
>             ApiConstants.DELEGATION_APP_OPS ->          R.string.label_delegation_app_ops
>             else -> return null
>         }
>     }
> ```

Additional delegated scopes can be added on demand, but only for scenarios targeting general public. If you need the new scope for your public app, please file a new feature request.

BTW, user restrictions are planned to be added in the future version of Island, as many users requested.
