### ISSUE TITLE
No wrench icon 

### ISSUE THREAD

**Issue by genevera** [oasisfeng/island#235]
I'm running island on a pixel 4a with Android 11.  I don't see a wrench icon next to island in setup as described in setup.md.  Am I just looking in the wrong place?  I really don't want to have to re add all of the various Google/exchange/blah blah accounts to my device if I don't need to.

**Comment by oasisfeng** [comment]
Sorry, that part of the setup guide is referring to the UI of old version. In the recent version, you can find the Island setup in "Discover" tab if your device is setup in God mode.

**Comment by genevera** [comment]
Ok and there's no one-tap install like there used to be to get God mode?

**Comment by oasisfeng** [comment]
Oh, sorry, I forgot that card was removed from Discover tab on Android 11+, due to changes in Android 11 which made the one-tap creation of Island no longer working.

"Demigod mode" is recommended on Android 11+. It can be activated after normal Island setup.

**Comment by genevera** [comment]
That setup involves removing all accounts from the phone, yes?

**Comment by oasisfeng** [comment]
> That setup involves removing all accounts from the phone, yes?

Unfortunately yes.
