### ISSUE TITLE
(Discuss)island only hide package instead of disable

### ISSUE THREAD

**Issue by NSTAdventure** [oasisfeng/island#236]
@oasisfeng 
why island only hide package instead of disable?

**Comment by oasisfeng** [comment]
Because DPC app cannot disable apps.

**Comment by NSTAdventure** [comment]
> Because DPC app cannot disable apps.

but did hide app will block their background behavior? how it's work? 🙏

**Comment by oasisfeng** [comment]
Hidden apps are just like being uninstalled, that's why they cannot run in background.

**Comment by NSTAdventure** [comment]
> Hidden apps are just like being uninstalled, that's why they cannot run in background.

ok thanks do dpc app able to suspend apps? (pm suspend)

i also remember icebox app freezer so this app also only hide another app instead of disable?

**Comment by oasisfeng** [comment]
> ok thanks do dpc app able to suspend apps? (pm suspend)

Yes.
