### ISSUE TITLE
{Question} Why Island use internet

### ISSUE THREAD

**Issue by Isssuemaker** [oasisfeng/island#239]
I have seen in Island manifest com.android.internet but why island use internet it is not good for privacy

**Comment by Isssuemaker** [comment]
Wanted answer from specially @oasisfeng  @Trumeet  @heruoxin

**Comment by oasisfeng** [comment]
For example, Firebase Crashlytics is used to collect crash statistics and provide information to help fixing issues on some edge cases that I cannot reproduce on my test devices.
