### ISSUE TITLE
How to use Files shuttle? 

### ISSUE THREAD

**Issue by lapsio** [oasisfeng/island#24]
I enabled files shuttle, how can I use it now?

**Comment by oasisfeng** [comment]
For any app supporting Android Storage Access Framework, in the file picker dialog, select the cross-border locations (with * mark) in the navigation drawer. There you can pick files in the other side.

**Comment by lapsio** [comment]
Thank you for your response. I noticed that files timestamps are not
preserved though (modification dates etc). Dates preservation in Android
has always been quite problematic - is it limitation of SAF itself? Or apps
I was using?

**Comment by oasisfeng** [comment]
> Thank you for your response. I noticed that files timestamps are not preserved though (modification dates etc). Dates preservation in Android has always been quite problematic - is it limitation of SAF itself? Or apps I was using?

Sorry, I'm not sure about this.

**Comment by macki-sushi** [comment]
Was trying to figure out how using the recommended file manager, I'm still unable to connect to the work profile (island) storage. is there anything I'm doing wrong perhaps?

**Comment by archont00** [comment]
As per https://island.oasisfeng.com/files
> Currently it enables apps (supporting Android SAF) in Island to access files in mainland. The reverse direction file access will be implemented in future version.

You do not neccessarilly need FX File Explorer to manually copy files from Mainland to Island as long as the cloned app (in Island area) can work directly with SAF (Whatsapp seems so).

**Comment by ambuvjyn** [comment]
The only solution that works till now is to use an app from play store called "Files Shortcut" by Delta 8 Studios. I dont know how he pulls it off but it works like a charm.

**Comment by IlluminatiWave** [comment]
> The only solution that works till now is to use an app from play store called "Files Shortcut" by Delta 8 Studios. I dont know how he pulls it off but it works like a charm.

It is just a shortcut to the native android file manager. That's why it seems to work... And I say seems because in Miui is unusable. I can only think of FTP ways like Xender

**Comment by 1054251** [comment]
Gracias ya la descargue espero me funcione igual Enviado desde mi OPPO de TelcelEl 7 feb 2023 10:03 a. m., IlluminatiWave ***@***.***> escribió:



La única solución que funciona hasta ahora es usar una aplicación de Play Store llamada "Files Shortcut" de Delta 8 Studios. No sé cómo lo logra, pero funciona a las mil maravillas.



It is just a shortcut to the native android file manager. That's why it seems to work... And I say seems because in Miui is unusable. I can only think of FTP ways like Xender
