### ISSUE TITLE
Manual Setting on Android 5.1.1?

### ISSUE THREAD

**Issue by Adim2P** [oasisfeng/island#25]
So I Did some research on what this app does and I got interested, but when I did recap the installation on how to do it, I can't seem to create a profile whatsoever, I'm still stuck with an error saying "Error: couldn't create profile" I did type setprop fw.max_users 10 but it doesn't show any complications nor error so I retried the pm profile command again and it still says Error: couldn't create profile are there any drivers or something that I'm missing?

**Comment by oasisfeng** [comment]
Could you please capture a logcat during the failure? If you are unfamiliar
with logcat, you can alternatively create a bug-report in system Settings -
Development settings.

**Comment by Adim2P** [comment]
Heres the bug report

**Comment by oasisfeng** [comment]
Sorry, I see no attachment in your email.

**Comment by Adim2P** [comment]
Sorry the attachment wont send its 12 mb to big for github can you send me
like a business email or personal email?

**Comment by oasisfeng** [comment]
It's the attachment size limit of your email provider. You can
alternatively send the large file with your favorite cloud storage service
(e.g. Dropbox, OneDrive, Google Drive) and share the file with a link sent
to me.

**Comment by muzeasd** [comment]
@Adim2P @oasisfeng  Any update on this issue?? I also face this issue and unable to manually setup on Lollipop.

**Comment by Adim2P** [comment]
@muzeasd Yeah same issue as well? Why don't you try sending your bug report txt file as well.

@oasisfeng Here's my bug report link: https://drive.google.com/open?id=1QdKdcUBFU4KeZF2r_rFc7IkAMy2ozZQk

**Comment by oasisfeng** [comment]
@Adim2P Sorry but I couldn't find anything related to the issue in the log from your bug-report.

Did you create the bug report immediately after the shell command failure? If so, could you please do that again and record and report the exact time of the shell command failure here, together with the bug-report?

**Comment by Adim2P** [comment]
Okay I will try, but I did that bug report after the adb shell commands.

**Comment by oasisfeng** [comment]
Closed due to lack of response.

**Comment by BenCat07** [comment]
Good day, i have the same issue and am actually able to provide a logcat. 

[logcat.txt](https://github.com/oasisfeng/island/files/5611985/logcat.txt)


Should be at the very top

**Comment by BenCat07** [comment]
(This is android 10 though)

**Comment by BenCat07** [comment]
[logcat.txt](https://githuHb.com/oasisfeng/island/files/5612000/logcat.txt)

Here is a second one where i waited a bit after logcat clear.
