### ISSUE TITLE
Signal messaging crash after each run

### ISSUE THREAD

**Issue by dlevequeIT** [oasisfeng/island#257]
Hello,
I use Island since more than 1 year and all was perfect until now.
I wanted to reset my Island Professional sandbox after the disapearement of some apps in the workplace env.

All previous installed apps have been re-cloned and works perfectly except Signal (the messaging app).
Signal work perfectly in the mainland but not in the Island. I tried to rollback with previous Signal version but not better.

I'm on OP7TPro (Android 11 Oxygen OS 11.0.1.1) and Island 5.4.3. Could you help me please ?

**Comment by oasisfeng** [comment]
App-specific issue requires logcat to investigate. Please upload the logcat somewhere and attach the link.

**Comment by dlevequeIT** [comment]
Hello. Thanks for the answer.
Please find logs collected after 2 try of launch Signal (org.thoughtcrime.securesms) :
[logcat_08-12-2021_11-51-34.txt](https://github.com/oasisfeng/island/files/6974514/logcat_08-12-2021_11-51-34.txt)

**Comment by oasisfeng** [comment]
Seems like an app-related bug, probably triggered by the running environment somehow different from Mainland.

Hope the following discussion may help on this issue: https://github.com/signalapp/Signal-Android/issues/9867

**Comment by dlevequeIT** [comment]
Hi,
Thank you for your return. I check the issue specified but the problem seems different, I saw no Exception related on Signal i my logs. I remember than Signal worked with Island 1 years ago but I tried to reinstall this version and it not works better.
In this interval there is some update from my OnePlus 7T and probably a new Android version from 10 to 11.

It seems that it's the enrollment phase of Signal which crash the application because 3 month ago it's work with Island
Do you know a workaround than I could tried to initialize enrollment on Signal ?

Thanks. Regards,
Damien

**Comment by dustball** [comment]
I am also experiencing this issue with signal. Is there anything I can do to help, like provide ADB logs?

**Comment by dlevequeIT** [comment]
Hello. There is around 2 weeks, I retried and it work now
I'm not changed any parameter and there was no android update.
All I know, it's than I'm on the release 5.28.8 of Signal and the release 5.5 of Island

**Comment by dustball** [comment]
I can confirm that updating signal to the latest beta fixes this issue.

**Comment by dlevequeIT** [comment]
Thank you for the feedback, I will close the issue.
Thanks for your help ;)
