### ISSUE TITLE
How to turn off Shuttle after revoking permission?

### ISSUE THREAD

**Issue by desmonk** [oasisfeng/island#265]
Once we enable the Shuttle, we can't disable it after revoking the permission using adb shell:
adb shell pm revoke com.oasisfeng.island android.permission.INTERACT_ACROSS_USERS

Shuttle box has a "Learn More" label instead of "Enable" option as it should get reset after preforming above command.

Thank you for your hard work!

**Comment by oasisfeng** [comment]
This permission is now permanently removed since new implementation of File Shuttle is introduced in Island 6.0.

**Comment by desmonk** [comment]
Thank you so much for the update!
