### ISSUE TITLE
File Shuttle not working for some apps like WeChat

### ISSUE THREAD

**Issue by Ayx03** [oasisfeng/island#268]
I'm just using island for installing another WeChat(bruh) on my LG V50 ThinQ(Android 10), so I would like island to allow the other WeChat to access my personal storage.
I refered to [this guide](https://island.oasisfeng.com/files), but it doesn't work, my second wechat still have no access to my main storage, and I don't know what's the “Discover” tab in Chinese. I didn't find any settings I could enable to give WeChat access to the mainland.
![Snipaste_2021-09-09_15-00-17](https://user-images.githubusercontent.com/75155322/132638447-4efa8863-fcb0-4566-822d-fd74a4a4cfc9.png)

**Comment by oasisfeng** [comment]
That's because WeChat does not use Android Storage Access Framework, so it could not benefit from File Shuttle.
