### ISSUE TITLE
华为mate8无法使用

### ISSUE THREAD

**Issue by dahuziqi** [oasisfeng/island#27]
安卓系统为8.0，安装后提示“壶中界的创建不完整，此前的创建尝试可能并未成功”，然后再提示删除现有的资料，若不取消，则如上反复循环。如选择取消删除，则可选“通过ROOT创建壶中界”，但点击该选项后，提示“抱歉，创建壶中界时出现了异常。（阶段1）”
[SVID_20190419_075039_1.zip](https://github.com/oasisfeng/island/files/3096530/SVID_20190419_075039_1.zip)

**Comment by oasisfeng** [comment]
![image](https://user-images.githubusercontent.com/181213/56404203-eac6ed80-6297-11e9-8c41-902700747664.png)

请按照上述提示操作后重试。

**Comment by dahuziqi** [comment]
衷心感谢！按您的指导，将软件设置为允许自启、允许关联启动、允许后台运行后，能运行了！
