### ISSUE TITLE
无法向壶内添加CA证书

### ISSUE THREAD

**Issue by LauKT** [oasisfeng/island#276]
我希望在壶里使用Adguard来过滤广告，需要安装CA证书来启用HTTPS过滤。但是Android 11开始好像只能通过DPC应用来向Work Profile里添加CA证书，希望大佬们指点一下如何添加证书，手机有su和magisk。

**Comment by oasisfeng** [comment]
目前有考虑增加这个特性。

这里的 CA 证书，是自己本地生成的？

**Comment by LauKT** [comment]
对，本地生成的，不知道除了壶App本身做这个特性之外还有没有其他方式添加了，比如terminal之类的，我手机有su。

oasisfeng ***@***.***> 于 2021年10月10日周日 17:12写道：

**Comment by LauKT** [comment]
大佬，你可以不必着急添加这个特性，其实直接代理8080也能实现个人资料+工作资料全部代理，不过确实有需要向工作资料里添加CA的场景。
