### ISSUE TITLE
[Greenify] keep greenify alive

### ISSUE THREAD

**Issue by giovEra** [oasisfeng/island#284]
Hi @oasisfeng,
first of all sorry for the off topic.

Could you update greenify to work on android 11?
If you don't have time to maintain it, could you make it open source?

Thank you for your work/apps.

**Comment by oasisfeng** [comment]
It's already working on Android 11, currently in beta channel.

**Comment by MultiKoopa** [comment]
> It's already working on Android 11, currently in beta channel.

Hello. It's been a while. Just got the Android 15 update for Greenify from the Google Play Store. Thank you!

I'm on a Pixel 9 Pro XL now, and the Donation Package for Greenify is listed as incompatible with my device. Could you please update the Donation Package? I've always loved Greenfiy; thank you for making it!

**Comment by rottweiller76** [comment]
same issue here, the program runs flawless, cant see/block the system files because the donation page says is not compatible anymore :(

**Comment by hmscott** [comment]
> It's already working on Android 11, currently in beta channel.

The Donation Package, which has worked for years now says it's not compatible...S24U just updated to Android 15 , One UI 7 :
Update information
. One Ul version: 7.0 • Android version: 15 . Version: S928USQU4BYD9 / S928UOYN4BYD9/ S928USQU4BYD9 . Size: 5563.22 MB ‣ Security patch level: April 1, 2025

Thank you so much for all you're hard work!

Maybe it's time for a new round of Donations to help with the work.  I paid years ago, and I wouldn't mind re-upping my donation.

I've also joined Beta on the Greenify app.
