### ISSUE TITLE
deactivate missing

### ISSUE THREAD

**Issue by zane-sano** [oasisfeng/island#289]
**How do I get the deactivate option?**

This app has a lot of open points and it's hard to stabilize it and get it working properly.

I left a long time off, where the workgroup icons were whitish. But I took it out of the freeze and I can't go back.

It had been difficult to freeze them all at once, but now that I'm back to using it, it only shows notification with links to `Restart` and `Settings`, missing `Deactivate`.

<kbd>**Island space is active**
Restart to reclaim all the resources used inside.
[Restart]() [Settings]()</kbd>

I don't know if it was Android 10 permissions, the update, or the MIUI optimization, or I just don't know how to access the freeze/deactivate all the Island for when I'm not using it.

PS I know about Greenify but I don't see the need to install it.

**Comment by oasisfeng** [comment]
It is back with new implementation in the latest alpha version. Please stay tuned for the beta update.

**Comment by zane-sano** [comment]
> It is back with new implementation in the latest alpha version. Please stay tuned for the beta update.

Thanks... You mean version 5.4.3 ? This is the one I have and the Deactivate is still missing... Maybe I shall to rebuild the Island? The repair didn't work.
