### ISSUE TITLE
INSTALL_FAILED_INVALID_APK missing codepath

### ISSUE THREAD

**Issue by penhauer-xiao** [oasisfeng/island#31]
Samsung note8 upgraded from android 8.0 to 9.0; then when the island upgraded to 3.5.3 ； clone to install application(Separate application from working outside to the island), the following error occurred:

INSTALL_FAILED_INVALID_APK missing codepath

**Comment by oasisfeng** [comment]
Please attach logcat if possible.

**Comment by penhauer-xiao** [comment]
@oasisfeng  How to do? for logcat.

The prompt that pops up is just this,  INSTALL_FAILED_INVALID_APK missing codepath

**Comment by penhauer-xiao** [comment]
@oasisfeng 

It's ok to unload the workspace, then uninstall the island, then re-install the island, and then apply the clone the app to the island from outside island. This is too expensive. There are a lot of things in the island; this is a big big bug.

**Comment by oasisfeng** [comment]
Please try the new version 3.6.1.

**Comment by penhauer-xiao** [comment]
@oasisfeng  OK

**Comment by oasisfeng** [comment]
@penhauer-xiao Is it fixed in v3.6.2?

**Comment by penhauer-xiao** [comment]
@oasisfeng  Yes, it working in v3.6.2 now.

Perhaps island 3.5.3 can cause problems with crashing and restarting the phone. I remember that my Samsung note8 was used for nearly two years and never automatically restarted. But shortly after upgrading to island 3.5.3, when using the island's APP (not sure which APP is causing it), my phone automatically restarts. Then after upgrading to 3.6.2, there is no restart now; I guess the version is caused by version 3.5.3.

**Comment by oasisfeng** [comment]
Thanks for your confirmation.
