### ISSUE TITLE
File manager with "cross-land capability"

### ISSUE THREAD

**Issue by goyalyashpal** [oasisfeng/island#310]
Hi!

## Summary
Query for Way to copy files in bulk primarily from work profile to personal profile

### Details
* i thought that giving file manager the "cross land privilage" will help, 
* but i cant find any file manager which have that capability
* so, Do you know how can i copy multiple files from work profile to personal profile?? like either any file manager which have cross land capability or maybe some other way.

### Prelude
* For sharing single image files across for use by apps, it can be done using "share with" buttons or "attach file" of many apps
* Even that poses problems some times, but i couldnt replicate the problems consistently there, and it is seeming to working fine now after some 2 weeks of use
* But things are very bad when it comes to copying/moving files from work to personal which are not common media files like .zip or files in bulk for example

|  |  |  |
| -- | -- | -- |
| ![image](https://user-images.githubusercontent.com/19423063/148983995-6ff12a60-ef04-4e40-8e7f-324767211286.png) | --> | ![image](https://user-images.githubusercontent.com/19423063/148984789-b8d3dc76-f99c-490f-8193-d18a921a6f21.png) |

### Versions:
* Island: 5.5.1
* Android: 11
* Flavour: realmeUI

**Comment by goyalyashpal** [comment]
oh, related discussion: https://github.com/oasisfeng/island/issues/85#issuecomment-668606195
🔍 : [file manager](https://github.com/oasisfeng/island/issues?q=is%3Aissue+is%3Aopen+file+manager)

so, this capability is granted via adb with command right?
`pm grant com.oasisfeng.island android.permission.INTERACT_ACROSS_USERS`

-----
i havent read that complete discussion, so, just guessing that my this issue is a duplicate then? should it be closed?

i am asking for your input on closure as that issue's title is the reverse direction of my use case. and i am not primarily having that problem.

**Comment by oasisfeng** [comment]
You can use File Manager that supports Android Storage Access Framework, such as [FX Explorer](https://play.google.com/store/apps/details?id=nextapp.fx) (Use "Connect to Storage" in the pull-down menu)

In the system dialog for selecting folder, you can switch to Mainland (Personal) or Island (Work).
![image](https://user-images.githubusercontent.com/181213/152467425-1b1d3603-defa-409a-8021-92436570f10c.png)

With the new File Shuttle implementation in Island 6.0, you can do two-way file copying in a single File Manager UI. So you can either use the file manager app in Mainland or Island.

**Comment by cooldroid** [comment]
I am unable to delete files in cross-land. I have tried FX Explorer also. It shows "Internal error".
![Screenshot_20220219-204635](https://user-images.githubusercontent.com/1247072/154807017-91a95c92-0e60-40d4-ac38-8a7f38ffc8c4.jpg)

May be this can provide more insight into the issue
![Screenshot_20220219-212140](https://user-images.githubusercontent.com/1247072/154808229-c882f0e4-3f23-4825-989e-aca01c0ff9cd.jpg)

**Comment by cooldroid** [comment]
@oasisfeng - can you please provide any insight into this, if my setup is wrong or if i am missing any permissions.

**Comment by plusmaa** [comment]
is there a open source alternative to FX Explorer that works with file shuttle? i tried a bunch but non worked.

**Comment by Zack12357** [comment]
pm grant com.oasisfeng.island android.permission.INTERACT_ACROSS_USERS        这个文件穿梭相关执行代码在旧版和新版6.0.5中是不是失效了或被禁用了？因为我发现执行这个代码命令没有任何反馈跟没执行一样，请问是怎么回事？

**Comment by Zack12357** [comment]
> 您可以使用支持Android Storage Access Framework的文件管理器，例如[FX Explorer](https://play.google.com/store/apps/details?id=nextapp.fx)（在下拉菜单中使用“连接到存储”）
> 
> 在用于选择文件夹的系统对话框中，您可以切换到大陆（个人）或岛（工作）。 ![图像](https://user-images.githubusercontent.com/181213/152467425-1b1d3603-defa-409a-8021-92436570f10c.png)
> 
> 借助 Island 6.0 中新的 File Shuttle 实现，您可以在单个文件管理器 UI 中执行双向文件复制。因此，您可以在大陆或岛屿中使用文件管理器应用程序。

你好作者，我的手机主空间和工作空间都装了FX Explorer，并且在主空间点击这个软件后右点了右上角三个点的“连接到存储”后出来个个人空间和工作空间，个人空间里显示有内容文件夹啥的，可是点击工作空间却什么都没有并且提示“无法选择工作文件，您的IT管理员不允许您通过个人应用访问工作文件夹”是啥意思。况且我也在工作空间打开FX发现个人空间正常显示内容文件夹啥的，可是工作空间依然跟主空间的FX一样不正常的提示这是怎么回事？麻烦解答下谢谢

**Comment by yzrsng** [comment]
> is there a open source alternative to FX Explorer that works with file shuttle? i tried a bunch but non worked.

I use this.
https://github.com/ianhanniballake/LocalStorage
