### ISSUE TITLE
在界外使用过分身的应用无法在界内再次安装

### ISSUE THREAD

**Issue by TrayBer** [oasisfeng/island#311]
实例：
界外安装了 微信读书app，通过 island 分身成功，后取消该分身。在界内直接下载微信读书apk安装包，安装始终失败（包括摧毁壶中界）。

环境：Android 12（类原生系统）

**Comment by oasisfeng** [comment]
可能界内下载的版本低于界外安装的版本。

建议调用 Island 的 应用安装器安装 apk，可看到具体的失败原因。

**Comment by TrayBer** [comment]
后来我卸载微信读书、island，重启手机再次安装island，界内可以通过Google 商店安装微信读书了。

**Comment by oasisfeng** [comment]
我理解，这个 issue 可以 close 了？

**Comment by TrayBer** [comment]
好的，感谢提供帮助。
