### ISSUE TITLE
Unable to clone non-system app to work profile with error message

### ISSUE THREAD

**Issue by modestderp** [oasisfeng/island#313]
## Summary
I am suddenly unable to clone apps to my island work profile. Whenever I try to clone app, a error message "**Internal error: Parcel: unable to marshal value com.oasisfeng.islad.controller.IslandAppCLones@<some hash>**" is displayed.

## Steps to reproduce
Select any non-system app in mainland and try to clone over to island work profile.

Samsung S10
Android 11, Dec 2021 security patch

## What is the current bug behavior?
Error message "**Internal error: Parcel: unable to marshal value com.oasisfeng.islad.controller.IslandAppCLones@<some hash>**" is displayed.

## What is the expected correct behavior?
App is successfully cloned to island work profile.

## Note
I have tried to repair several times to solve the issue but it doesn't seem to help.

**Comment by oasisfeng** [comment]
Which version of Island?

**Comment by modestderp** [comment]
My apologies. It seems the issue is not with Island but with a fork. The issue seems to have resolved with the latest build from the fork. I will close this issue.
