### ISSUE TITLE
Can't clone app when island is not active

### ISSUE THREAD

**Issue by the-Arioch** [oasisfeng/island#314]
Trying to clone any app i get a strange error

```
Unknown URI: content://10@com.oasisfeng.island.shuffle
```

I do not have Shuffle enabled via ADB, but i also do no ask for Shuffle, i just want to clone an application!

If i have the island (work profile) running, then cloning is done okay.
![2022-01-25 23_14_04-Screenshot_20220125-223902](https://user-images.githubusercontent.com/937774/151052678-0470bf4f-8251-4026-b485-802488e6155d.png)

Island 5.4.3 (Google Play - early)

**Comment by oasisfeng** [comment]
Fixed in be00122073109e1e10b8d2a5add5c1cbebd181c4
