### ISSUE TITLE
Cloned AliExpress can not download llocalization

### ISSUE THREAD

**Issue by the-Arioch** [oasisfeng/island#315]
Island 5.4.3 (Google Play - early)

https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd

After cloning i try to switch the application language - and it gives me download error.

Mainland application downloads and switches UI okay, but one inside the Island persistently fails.

![2022-01-25 23_09_03-Screenshot_20220125-224745](https://user-images.githubusercontent.com/937774/151053548-ce54b38e-4308-4284-9be4-f34727ec6b56.png)
![2022-01-25 23_23_05-Screenshot_20220125-224800](https://user-images.githubusercontent.com/937774/151053901-d3ebccf5-53ac-440b-8c56-01887a497f6d.png)

**Comment by oasisfeng** [comment]
This is an issue in that specific app, please report it to its developer.

**Comment by the-Arioch** [comment]
isn't it island that simulate normal working environment for programs?

what specifically can be reported to their dev? island is hardly what app
devs test again

**Comment by oasisfeng** [comment]
Some app are not developed following the rules of Android development, causing troubles running in multi-user environment.

You can ask the developer to test it in secondary user.
