### ISSUE TITLE
如何在界内使用不同的输入法？

### ISSUE THREAD

**Issue by TrayBer** [oasisfeng/island#316]
类原生系统使用island，自带Google的Gboard输入法，如何在界内使用不同的输入法，例如搜狗、百度输入法？

**Comment by oasisfeng** [comment]
在界内安装想要的输入法即可。

**Comment by f2sky** [comment]
尝试安装了搜狗、百度输入法，输入时不能调起，还是自动弹主系统输入法。

是否需要特别的设置？

**Comment by TrayBer** [comment]
> 在界内安装想要的输入法即可。

尝试安装了搜狗、百度输入法，输入时不能调起，还是自动弹主系统输入法。

是否需要特别的设置？

**Comment by oasisfeng** [comment]
取决于你的系统设置是否提供了针对不同用户（工作资料）的输入法设置。
