### ISSUE TITLE
Required "Android For Work"

### ISSUE THREAD

**Issue by lanson5209** [oasisfeng/island#319]
![Screenshot_20220129-155002](https://user-images.githubusercontent.com/98370362/151654539-6d8fa41f-83d2-4896-8ab2-f0a76e3805e1.jpg)
any solution for this problem?

**Comment by Hydra119** [comment]
Yea, don't use Android 10/11. I've had the same problem on my Tinno Wiko Life 3 (U316AT), & a Scepter 8 tablet. 🙁
