### ISSUE TITLE
Android Q background activity restrictions

### ISSUE THREAD

**Issue by Mygod** [oasisfeng/island#32]
Using developer options isn't a long-term solution. Device owner mode might be favorable. Source: https://developer.android.com/preview/privacy/background-activity-starts#conditions-allow-activity-starts

Also I noticed that `buildManagedDeviceProvisioningIntent` is implemented (partially?) but never used. Is there any reason for preferring `ACTION_PROVISION_MANAGED_PROFILE`?

**Comment by oasisfeng** [comment]
Never a long-term solution. As the restriction and its behavior constantly changes through beta 2 ~ beta 4, it's not wise to adopt to it too early.

**Comment by oasisfeng** [comment]
Solved in the latest alpha version.
