### ISSUE TITLE
How to use Mainland Files (pictures, pdfs) into Island and Viceversa?

### ISSUE THREAD

**Issue by Itsmesri** [oasisfeng/island#324]
I have activated File Shuttle in Discovery using https://island.oasisfeng.com/files. I am using Samsung Fold3. Still, don't understand how to access Mainland files in IsLand?

Someone provide me step by step please

**Comment by oasisfeng** [comment]
Since Island 6.0, the old File Shuttle is replaced by new implementation, which requires no setup at all.

**Comment by Itsmesri** [comment]
PlayStore has 5.4.3 version. where can I get latest?

**Comment by oasisfeng** [comment]
This is GitHub.
https://github.com/oasisfeng/island/releases
