### ISSUE TITLE
VPN connection at island environment & Gapps issue

### ISSUE THREAD

**Issue by crazysoft** [oasisfeng/island#33]
@china mainland,well known firewall.
I installed gapps,so com.android.vending also in my island environment. It always trying connect to Google and wwwwwwwwwwwasting my battery.
Any way I can solve this issue? Open island environment VPN?or batter idea? Thanks.

**Comment by oasisfeng** [comment]
You can freeze Google Play Store and Google Play Services and unfreeze them on-demand.
