### ISSUE TITLE
[问题]用island创建快捷方式,可以启用(notification badges通知徽标)吗?[建议]可以手动选择软件 (language语言)

### ISSUE THREAD

**Issue by gmrsuns** [oasisfeng/island#330]
目前island岛内的应用可以正常工作,但创建的快捷方式不显示 (notification badges通知徽标),请问有这个功能嘛.另外也希望island能创建一个TG交流群

**Comment by oasisfeng** [comment]
支持 Badge 相关的特性需要 launcher 支持，单靠 Island 目前还做不到。

**Comment by gmrsuns** [comment]
创作者你好,很高兴能使用island,关于notification badges的问题原因和临时解决方法我已经找到了
原因,如果使用islan创建的岛内快捷方式,在(microsoft.launche微软桌面)和手机自带(launcher桌面) 我这是无法显示 notification badges.
我目前使用了 (microsoft.launcher微软桌面),在工作区,直接拖出岛内应用即可显示notification badges.
最后感谢作者给我们带来了island
也希望可以搞个 TG交流群,大家互相交流和传递island使用心得,也会让作者减轻负担
