### ISSUE TITLE
壶中界应用调用输入法崩溃

### ISSUE THREAD

**Issue by ghost** [oasisfeng/island#339]
系统为AOSP的修改版安卓11，最近发现壶中界大部分应用在调用输入法时都会自动崩溃i，目前壶中界的微信暂时还没出现此问题，请问我该如何排查

**Comment by ghost** [comment]
这个现象出现于我更新了部分lsposed模块之后，换用谷歌拼音输入法发现问题相同，而壶中界的应用是否正常调用输入法并未体现出与修改对应应用的模块有关联，比如贴吧切换模块开关后依然会闪退

**Comment by oasisfeng** [comment]
需要 logcat 或 bugreport 才能具体分析。

**Comment by ghost** [comment]
更换其他版本的系统没有出现类似故障，感谢回复
