### ISSUE TITLE
Feature Request: Ability to import/export entire island to another device(apps+data)

### ISSUE THREAD

**Issue by scottydelta** [oasisfeng/island#35]
I have been installing and using most of the apps on the sandbox/island provided by island app on Android, It would be nice to have an ability to export and import an entire island(all apps and data) for ease of portability.

**Comment by oasisfeng** [comment]
This is effectively an apps backup / restore feature, which is already working from 3rd-party apps backup tools. So Island has no plan for that.

**Comment by scottydelta** [comment]
I have been unable to backup any apps from island using titanium or oandbackup. Both apps dont work once installed inside island.

**Comment by nettnikl** [comment]
@oasisfeng Could you maybe explain how to enable the use of Titanium backup inside the Island? As pointed out by @scottydelta I am not able to use it for backups, neither from inside the Island (Titanium not working) nor from the outside (app is invisible to Titanium).
Currently I have to manually backup sandboxed apps.
If there is a simple solution to this problem it may be worth to add it to the README.

**Comment by oasisfeng** [comment]
I'm not sure whether Titanium Backup supports Android multi-user mechanism. Please ask the developer of Titanium Backup instead.

If a backup tool supports multi-user merchanism properly, it should work with Island too.

**Comment by scottydelta** [comment]
from my limited research, Android doesnt support backup of Work profile. I have tried multiple apps(titanium pro and some others) to get the backup of Work Profile/Island app but failed.

**Comment by nettnikl** [comment]
It should be theoretically possible without much work, as a simple file explorer is able to extract private data from apps. But, as you said @oasisfeng , this seems to be an issue the backup app developers have to address.  
For reference, on my device the encryption key of a messenger app i installed on the island is located at /data/user/10 (instead of /data/data).

**Comment by nettnikl** [comment]
Thank you for pointing that out @scottydelta, i also had trouble finding a workin backup app. Did you have any luck, and give me a recommendation for an application that support work-profile backups, atleast on rooted devices? Or do you also manually backup the sandboxed apps now?

**Comment by scottydelta** [comment]
> Or do you also manually backup the sandboxed apps as a workaround for now?

this

**Comment by qazmko1029** [comment]
I'm able to use Titanium backup in work profile with Magisk installed and setting its multiuser mode>User-Independent. But I can't direct the backup path to mainland.

**Comment by Antar-git** [comment]
Using swift backup with magisk(root) or shizuku(non root) i can backup installed app and their data and copy them to mainland using fx file manager .
But if there was any option to back up everything in the island settings with shizuku or root it would be great to restore them
