### ISSUE TITLE
Hidden icons appear on launcher after creation 

### ISSUE THREAD

**Issue by Guanran928** [oasisfeng/island#406]
After I created a island, there's multiple app appeared on my launcher(and should be hidden, such as IME, pixel launcher and microG)
当我创建工作资料后 我的桌面上多出了原本隐藏的应用（输入法，pixel启动器，microG等）

I've already tried reinstalling those apps and removing island
尝试过删除工作资料和重装隐藏软件

![Screenshot_20230110_031103_com huawei android launcher](https://user-images.githubusercontent.com/68757440/211896658-d37c3bb8-e0a8-4839-b6ee-03f304857f29.jpg)

**Comment by scruel** [comment]
adb shell pm list users 
adb shell pm uninstall --user XXX com.package.xxx

**Comment by Guanran928** [comment]
No longer using the original device
