### ISSUE TITLE
god mode 失效

### ISSUE THREAD

**Issue by cc9014** [oasisfeng/island#41]
昨天激活成功，今天发现黄帝之名没了，需要重新激活。。。

**Comment by oasisfeng** [comment]
反馈问题请注明机型、ROM、Android 版本、Island 版本。

另外，激活之后到失效前，有进行过什么可能有联系的操作？

**Comment by cc9014** [comment]
机型：华为Mate9
ROM：EMUI 9.1.0
Android版本：9
Island版本：3.8
好像没进行过有联系的操作，就关联了AppOps……

我今天又重新激活了一次，看看还会不会失效。
