### ISSUE TITLE
project maintained?

### ISSUE THREAD

**Issue by SynapseScribe** [oasisfeng/island#422]
there hasn't been any commit since Sep 2, 2021. Is there any future for this project?

**Comment by AshKxK** [comment]
I mean he moved onto play store, but aince he wont answer idk anymore.

**Comment by SynapseScribe** [comment]
i am using insular which is open source for the past 2 years and works like a charm

**Comment by oasisfeng** [comment]
> there hasn't been any commit since Sep 2, 2021. Is there any future for this project?

The main development branch is "dev".

**Comment by SynapseScribe** [comment]
may I ask what keeps it from releasing a new stable release at least with some of the bugfixes that have been added? thank you
