### ISSUE TITLE
Island keeps stopping on android 13

### ISSUE THREAD

**Issue by sgitsp** [oasisfeng/island#433]
Hi,

Been using island for quite some time on version 6.0.5, its works fine. Just installed the 6.1.0 pre-release version this morning and found it doesn't run on android 13. Now I'm stuck and can't downgrade except by deleting the work profile entirely

**Comment by oasisfeng** [comment]
Sorry for the trouble.

It should now be fixed in v6.1.1 released just now.

**Comment by sgitsp** [comment]
Great! Thanks for your response. It works but there is a new bug when creating a new profile.

At first, checked with `adb shell pm list user` there's a new profile named Island, but the app threw an error when provisioning profile then advised me to setup manually. I tried to delete the work profile manually with adb and installing the old v.6.0.5 and it worked fine without the need for manual setup.

I don't understand if this is a bug from the app or from android itself.

**Comment by PixelCode01** [comment]
> 

If you are setting up Island for first time don't open the app and create a work profile instead do full setup using adb

**Comment by oasisfeng** [comment]
> Great! Thanks for your response. It works but there is a new bug when creating a new profile.
> 
> At first, checked with `adb shell pm list user` there's a new profile named Island, but the app threw an error when provisioning profile then advised me to setup manually. I tried to delete the work profile manually with adb and installing the old v.6.0.5 and it worked fine without the need for manual setup.
> 
> I don't understand if this is a bug from the app or from android itself.

That should have been fixed in v6.1.2.
