### ISSUE TITLE
island 可以支持 Insular 这样的 VPN 特性么？

### ISSUE THREAD

**Issue by TrayBer** [oasisfeng/island#434]
**Insular**：island 的复刻项目，地址：https://f-droid.org/packages/com.oasisfeng.island.fdroid/
其中一个特性：`Selectively enable (or disable) VPN for different group of apps`

island 会提供这个支持么？

**Comment by oasisfeng** [comment]
这是 VPN 工具 app 可以支持的特性，Island 只隔离各个空间的 VPN 独立性。
