### ISSUE TITLE
Auto DeGreenify with Tasker

### ISSUE THREAD

**Issue by Djtrip83** [oasisfeng/island#45]
I am trying to guess the shell or intent code supporting the unfreeze shortcuts so I can automate with Tasker. It would be helpful to update the Greenify plugin or have something equivalent so that I can automatically degreenify app from deep island hibernation under certain conditions without having to create an unfreeze shortcut for the app

This is a feature rather than an issue.

**Comment by oasisfeng** [comment]
Sorry, this is the issue tracker of Island, not Greenify.

If you mean unfreeze (not de-greenify), the shell command is "`pm unhide [--user <user ID>] <app ID>`"

e.g.

`pm unhide --user 10 com.google.android.apps.foo`

**Comment by Djtrip83** [comment]
Sorry. I thought there was a dependency to Island. Thanks for the answer provided. That is what I was looking for.
