### ISSUE TITLE
Notch in island on Android 9, prob 10?

### ISSUE THREAD

**Issue by Beybarro** [oasisfeng/island#46]
Hey, I've played pokemon go for a long time with two accounts on the same phone thanks to island, but there's something annoying me since a lot of time
On the non island version, there's no problem about fillscreen with the notch, when the app is in this mode, it doesn't consider the notch
But when I put the island version in fullscreen, it is taking the notch on consideration, and put a black bar on the top to "hide" the notch (even though I'm still seeing time battery and notifs)

So probably a bug with the notch gestion

**Comment by oasisfeng** [comment]
Sorry, there nothing Island could help on this, it depends on the OEM implementation (ROM) of Android for Work.
