### ISSUE TITLE
Notification Permission Grayed Out: App Watcher Activation Issue Post-Update 

### ISSUE THREAD

**Issue by PixelCode01** [oasisfeng/island#474]
Unable to activate App Watcher due to the "Allow Notification" option being grayed out in Android settings. This problem emerged after the most recent update.
![Screenshot_20240110-002325](https://github.com/oasisfeng/island/assets/105023758/a6055df9-8deb-4ae3-9478-6ab7be9b66dc)

**Comment by boggleboggle** [comment]
I also have this problem.

**Comment by chaoticpunx** [comment]
Same problem here since updated to One UI 6.0 (Android 14)

**Comment by kahoch** [comment]
same problem, V6.3

**Comment by kevinlyliu** [comment]
Yes, confused. App watcher is the most frequently used feature in Island...

**Comment by lisinho** [comment]
Same Android 14

**Comment by MoonLeeeaf** [comment]
same problem, Island 6.3, Android 13, MIUI 14
![Screenshot_2024-04-13-07-00-22-439_com android settings-edit](https://github.com/oasisfeng/island/assets/150461955/5e471477-6ccc-49b9-bc2a-34d87fc373fe)
