### ISSUE TITLE
更新 Android 10 后如何再次启用文件传送门?

### ISSUE THREAD

**Issue by notastudio** [oasisfeng/island#49]
系统更新前启用过文件传送门,并且可以在工作资料中正常地访问机主的文件.更新后,按照 [https://github.com/oasisfeng/island/blob/gh-pages/files.md](https://github.com/oasisfeng/island/blob/gh-pages/files.md) 的说明在 adb shell 里执行了命令,但"天书"里没有出现启用文件传送门的按钮,也无法通过文件管理器跨工作资料访问.请问该如何解决?谢谢.

**Comment by Bakchosy** [comment]
没有出现"文件传送门"的启用按钮，是因为"文件传送门"功能已经启动了，你在系统更新前输过adb命令了。
无法通过"文件"跨境文件传输，是因为Island的"文件传送门"功能，在Android10上已经失效了。

Android10的跨境文件传输，可以通过FX的Share功能实现。

具体实现方法：
主机->炼妖壶:  在主机、炼妖壶，各自安装上FX(FX File Explorer)，授予FX"存储空间"权限。
                         在主机上打开FX，选中文件->Share(右上角3点)->选择"切换到工作资料"->分享 
                         到"FX"->选择位置，保存
炼妖壶->主机: 略，类比上条。

Android10的跨境文件传输，参考https://github.com/oasisfeng/island/issues/81，感谢Phusionraz的分享。

**Comment by oasisfeng** [comment]
v4.1 版本已修复。
