### ISSUE TITLE
Request: Please make auto-freeze the default

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [oasisfeng/island#51]
Many applications on our mobile phones are constantly chattering and sending our personal data back to the tech organizations without our "conscious" consent. Blocking this by default whenever a sandboxed application is closed is necessary for the sake of the tech-illiterate who want privacy but are unaware of its technical details.

I also recommend merging the Greenify app into this one please. IMHO, the general public may find the need to download two apps a burden.

Thank you in advance.

**Comment by oasisfeng** [comment]
Island is not solely for freezing apps, many users just take it as an app cloner. That's why this can't be default.

There's no plan to merge Greenify and Island, partly due to the reason above.
