### ISSUE TITLE
Partially initialized Island space

### ISSUE THREAD

**Issue by MaEGandi** [oasisfeng/island#526]
Please what happened to my island,it doesn't work on my device 
![Screenshot_20240526-071431](https://github.com/oasisfeng/island/assets/170849716/a6a92bc5-7bf9-450c-b0f5-6de716aa039a)
![Screenshot_20240526-071438](https://github.com/oasisfeng/island/assets/170849716/726308d5-3b04-4366-b8d8-7a2e9f001e98)
Please help me

**Comment by oasisfeng** [comment]
You need to remove the work profile from your device's system settings before recreating the Island space.

It should be in system Settings - Accounts or Users.
