### ISSUE TITLE
Add language option

### ISSUE THREAD

**Issue by NewUserHa** [oasisfeng/island#62]
my system is a language and I want the app display in another language.

thanks!

**Comment by NewUserHa** [comment]
#34

**Comment by ghost** [comment]
Yes, please. This would be a usefult thing. I usually use the apps with the default language, because it fits most cases. But for "system" apps, that require debugging, English is a better choice, because it makes bug reports easier.

**Comment by oasisfeng** [comment]
Sorry, I've already tried that, but it seems technically impossible due to the enforcement of device-wide language consistency in Android system.

**Comment by ghost** [comment]
OsmAnd somehow manages to do it.

**Comment by oasisfeng** [comment]
> OsmAnd somehow manages to do it.

Could you explain it in details? I searched and it seems like a normal app?

**Comment by ghost** [comment]
I don't know the detail unfortunately, but it's it has the UI to change the language.

![Screenshot_20211104-195203__01](https://user-images.githubusercontent.com/2077025/140309099-6750e40d-3b9e-42d2-af84-a6b599ba8577.jpg)

**Comment by oasisfeng** [comment]
Oh, I see. It's a functionality of the app.

That's easy to implement in separate app, but hardly possible in the Android system side.

**Comment by NewUserHa** [comment]
thanks!
hope island app itself can use a different language with the android system.

**Comment by DanielKnourek** [comment]
Perhaps with the new Android 13, there is a feature to have custom language setting for each app (That supports it) . 
I have tried it, but no luck on my Pixel 5.
