### ISSUE TITLE
炼妖壶内应用可以通过绝对路径访问外置sd卡

### ISSUE THREAD

**Issue by yutouyes** [oasisfeng/island#69]
- 设备是LG G7，系统是LG官方推送的安卓Q。机子可以插一张micro sd卡。

我用炼妖壶目的是隔离开毒瘤应用，不让它们访问和未经许可上传我的文件，所以没有开文件传送门，也没有分身magisk manager提供root授权
![503246_def3b0cd_2086_1284@1440x3120 jpeg m](https://user-images.githubusercontent.com/17039457/74898815-fca48000-53d5-11ea-81ae-4a54cb6d2f44.jpg)

![503246_d6fad6eb_2086_1288@1440x3120 jpeg m](https://user-images.githubusercontent.com/17039457/74898825-029a6100-53d6-11ea-9c4f-15ea3207d91f.jpg)

![503246_cb719368_2086_1286@1440x3120 jpeg m](https://user-images.githubusercontent.com/17039457/74898964-7472aa80-53d6-11ea-83ae-f94980fdefe8.jpg)

可以看到没有打开炼妖壶·彼界，理论上炼妖壶的应用是只能访问工作资料内的目录的。
但是对于可以输入绝对路径的app，比如root explorer，快图浏览，MT管理器，它们可以通过访问/storage/xxxx-xxxx直达我的内存卡
![503246_f6aed3c2_2086_1291@1440x3120 jpeg m](https://user-images.githubusercontent.com/17039457/74899147-067ab300-53d7-11ea-8164-103b41b1167e.jpg)

![503246_887ba445_2086_1301@1440x3120 jpeg m](https://user-images.githubusercontent.com/17039457/74899158-0b3f6700-53d7-11ea-9cd3-38aaeb0b4528.jpg)
尽管没有写权限，但是可以读取，也可以复制文件出来。

- 当selinux状态为permissive时，这些应用可以直接访问到/目录，包括/storage/xxxx-xxxx目录在内都有读权限，selinux状态为enfocing时，壶中界的应用最高只能访问到/storage，且无法访问/storage/emulated/0目录，该目录权限为0770。但内存卡目录/storage/xxxx-xxxx权限是0755，可以读和复制。权限无法修改。

是否有什么途径可以禁止壶中界（工作资料）内的app访问外置内存卡的目录呢？设备已root已解锁bootloader

**Comment by oasisfeng** [comment]
很遗憾，SELinux 是 Android for Work 实现存储隔离的必要环节。

请务必使用 SELinux 为 enforce 的 ROM。

**Comment by daiaji** [comment]
@oasisfeng 
能不能通过在SAF里开个传送门的方式绕过安卓11的SAF不能读写根目录的限制？
用root或者shizuku,其他的高权限绕过？
![Screenshot_20220226-222918215](https://user-images.githubusercontent.com/25875791/155847076-9bf0d9d6-53d5-4faf-954d-42a592adeb3f.jpg)
![Screenshot_20220226-223010404](https://user-images.githubusercontent.com/25875791/155847080-04823104-0419-4a1b-ac83-53628084b97c.jpg)
