### ISSUE TITLE
ice box 无法使用

### ISSUE THREAD

**Issue by z5n0w** [oasisfeng/island#74]
红米K20 Pro，MIUI11 11.0.5， Android 10
切换工作模式为island后 ice box重新启动到设置页面 工作模式仍为adb
island已授予管理员权限

**Comment by oasisfeng** [comment]
IceBox 需要 Island 工作在 god mode。

**Comment by z5n0w** [comment]
god mod 没看到开关， 设定为管理员就是GOD MOD的话
已经处于GOD MOD 了

**Comment by oasisfeng** [comment]
设定为管理员并不是 god mode。

God mode:
https://island.oasisfeng.com/setup#manual-setup-for-island-in-god-mode
