### ISSUE TITLE
Can you add an option to hide icons from the launcher for apps in your workspace?

### ISSUE THREAD

**Issue by monkey000** [oasisfeng/island#8]
Can you add an option to hide icons from the launcher for apps in your workspace? The launcher always shows two "files" and "address book" icons that make me feel bad.

能否为壶中界内的app加入从启动器中隐藏图标的选项？启动器总显示两个"文件"、"通讯录"图标让我感觉很难受。

**Comment by oasisfeng** [comment]
Island cannot hide app launch icons, except freezing them. Contacts and Files are not only system apps with launcher icons, but also key system components providing essential functionality. If you freeze them, you may find some function in the system not working properly.

For example, if you freeze Files, then the file picker invoked by some apps will not work.

**Comment by oasisfeng** [comment]
To hide launcher icons, you may use a 3rd-party launcher with "hide icons" feature. Or you can try Android 9-based launcher, which will group all apps in Island in a separate tab, along side apps in mainland.

**Comment by monkey000** [comment]
> To hide launcher icons, you may use a 3rd-party launcher with "hide icons" feature. Or you can try Android 9-based launcher, which will group all apps in Island in a separate tab, alongside apps in mainland.

Thank you for your answer. I understand

**Comment by monkey000** [comment]
I tried a lot of launchers and ended up using the Lawnchair V2 launcher.Feel good, support icon packs and more settings.
