### ISSUE TITLE
Info: Transferring files between mainland and island through file sharing

### ISSUE THREAD

**Issue by Phusionraze** [oasisfeng/island#81]
Not really an issue, just a bit of info for those having the same problem. 

I was having difficulties transferring files between mainland (ML) and island (IL) per the official [file shuttle instructions](https://island.oasisfeng.com/files) using FX File Explorer (FX) as selecting IL-FX's "Connect to Storage" only gave this warning:

**ERROR
This device does not appear to support the Android Storage Access Framework.
(Error: ACTION_OPEN_DOCUMENT_TREE not implemented by device.)**

I found however that file transfers are possible through file sharing, if FX (or presumably another SAF-supporting app) is used for the initial share action.

- ML->IL transfer: In ML, navigate to and select desired file using FX -> Share -> select "Switch to work profile" -> select FX, Save As (if FX is installed in IL) -> confirm save location.

- IL->ML transfer: In IL, navigate to and select desired file using FX -> Share -> select "Switch to personal profile" -> select FX, Save As (if FX is installed in ML) -> confirm save location.

If a non-SAF app is used the user will be able to follow these steps to the other M/I-land's directory, but the actual transfer will fail (you will probably get an "Internal error" warning or similar).

My settings/system, for reference:
- Island app version: 3.8
- FX app version: 8.0.1.0
- System: Android 10
- Device: Moto One Action
- Rooted: No
- Island God Mode enabled: No
- Island work profile active: Yes (but not necessarily showing in the status bar)
- Permissions: Island granted [INTERACT_ACROSS_USERS](https://island.oasisfeng.com/files), Storage*, and Device Admin app status*. FX granted Storage*, but not Location*.
*For both ML- and IL-version of app.

**Comment by oasisfeng** [comment]
File Shuttle now works on Android 10+ in Island v4.1.

**Comment by zarc2021** [comment]
The newest version of FX Explorer is completely broken. Cannot give access to SD Card at all because of the blank screen, while previously there's some "different folder" thing preventing access to SD card.
