### ISSUE TITLE
No permissions allowed

### ISSUE THREAD

**Issue by roshin8** [oasisfeng/island#88]
I noticed that for some of the apps, no permissions are allowed and they can't be changed (For Eg: Facebook Messenger in Island mode) - I wanted to use the Storage option but I'm not able to change it. In the App Info, it says the  **permissions are disabled admin**. I see no option in Island to change the permissions.
**App-Ops** is also set to allow all permissions but it still doesn't work even though I've enabled **Preserve App-Ops for frozen apps** in Island
But for some other apps like **Offer Up**, **Text Now**, the permissions can be changed without any issue. 

I wanted to understand why this is happening and if there is a work around for it. 

Thanks

**Comment by oasisfeng** [comment]
It's caused solely by AppOps. That description is misleading.

Please report to the developer of App Ops.
