### ISSUE TITLE
There is no option to "create thaw and launch shortcuts" in the app menu item in the workspace

### ISSUE THREAD

**Issue by monkey000** [oasisfeng/island#9]
When I uninstall the app in normal mode, there is no option to "create thaw and launch shortcuts" in the app menu item in the workspace.
And I can't launch the app directly from the island app list, I can only unfreeze it manually, then I can find the icon of the app from the launcher.

当我将正常模式内的app卸载后，壶中界内的app菜单项就没有"创建’解冻并启动‘快捷方式"的选项了。
并且我无法直接从壶中界列表中启动这个app,只能手动解冻，然后再从桌面找到app的图标启动。

**Comment by oasisfeng** [comment]
Fixed in v2.9.3.
