### ISSUE TITLE
关于 SafetyNet Check的问题

### ISSUE THREAD

**Issue by UFO-HQ** [oasisfeng/island#90]
安装island后Safetynet Check状态改变：
ctsProfile:false
basicIntegrity:false
Play Protect certification(Google play)状态改变:
Device is not certified

设备：ONEPLUS A5000
环境：官方OxygenOS 9.0.11(Android 9.0)
            已通过Magisk获取root权限

**Comment by bluehomewu** [comment]
你是指主用戶
還是island內的用戶?

**Comment by oasisfeng** [comment]
Island 不会改变 SafetyNet 状态。

你遇到的更可能是由于 Magisk Root 已经无法通过最新升级后的 Google Play 组件的新检测机制。
