### ISSUE TITLE
Cannot change Permissions for Apps

### ISSUE THREAD

**Issue by roshin8** [oasisfeng/island#91]
I installed Messenger within the Island mode (cloned it from Mainland). However, I'm not able to grant permissions to grant Storage or any other permissions. It says "Disabled by Admin"

I don't have App Ops or Shizuku Installed. I tried it with them but either way, I'm not able to change the settings.
![Screenshot_20200515-230403_Permission controller](https://user-images.githubusercontent.com/16354626/82110064-22090780-9701-11ea-9bd3-249b0a55a3d2.jpg)
![Screenshot_20200515-230705_Permission controller](https://user-images.githubusercontent.com/16354626/82110065-22a19e00-9701-11ea-8d49-7574145fc420.jpg)

**Comment by roshinv** [comment]
No longer happening in the new version

**Comment by roshin8** [comment]
No longer happening in the new version
