### ISSUE TITLE
打开“文件传送门”后，adb被关闭，点击系统版本号弹出“不允许执行此操作”

### ISSUE THREAD

**Issue by aalennku** [oasisfeng/island#96]
现在问题是，我不能点击系统版本号也就不能打开开发者选项，也就不能打开adb，无解了 也就不能取消炼妖壶管理授权，刷机都不行 怎么办。

点击系统版本号说
“不允许执行此操作 如需取消此限制，请至应用中调整相应的设置。”

**Comment by oasisfeng** [comment]
Island - Discover - 关闭 ADB Secure。

**Comment by xuu777** [comment]
同问阿.你的问题解决没有阿.

**Comment by xuu777** [comment]
> Island - Discover - 关闭 ADB Secure。

Island APP里没有发现 Discover  这个选项啊.能说清楚点吗,谢谢了...
