### ISSUE TITLE
如何使用vpn

### ISSUE THREAD

**Issue by einsam1970** [oasisfeng/island#99]
界外google play等软件通过VPN能正常登陆，但是把play、相册等软件放到壶中界后，不论在界外还是壶中界内运行VPN软件，都卡在登陆界面
![Screenshot_20200607_080406_com google android gms](https://user-images.githubusercontent.com/66540122/83958227-0d540580-a8a2-11ea-9427-de99860c1cdd.jpg)，结果无法登陆
![Screenshot_20200607_080419_com google android gms](https://user-images.githubusercontent.com/66540122/83958234-1644d700-a8a2-11ea-8c6b-e66b13ac3d1e.jpg)
华为手机，
操作系统emui:10.0.0.200
炼妖壶版本:4.1

**Comment by oasisfeng** [comment]
这是手机系统（ROM）的机制实现，Island 对此无能为力。

正常情况下，需要在 Island 空间内开启 VPN 服务才能代理空间内应用的网络请求。
